/**
 * Pure engine for the scenario recorder: shared by the main process (which groups captured
 * input into actions and compiles a scenario into replay steps) and the renderer (the review
 * screen, which edits the timing and the typed text of actions and deletes them). No Electron
 * imports here, and no I/O – everything is deterministic given its inputs, which is what makes
 * it unit-testable without a real capture.
 */
import { SCENARIO_MAX_MS } from './defaults'
import type {
  Scenario,
  ScenarioAction,
  ScenarioActionKind,
  ScenarioClickAction,
  ScenarioDragAction,
  ScenarioKeyAction,
  ScenarioModifiers,
  ScenarioPathPoint,
  ScenarioPoint,
  ScenarioScrollAction,
  ScenarioShot,
  ScenarioTypeAction
} from './types'

// ---- raw capture events ----
// The capture module (src/main/scenario/capture.ts) turns uiohook/polling events into this
// union, in chronological order. Every event that can *start* a new action carries an `id`
// generated by the capturer (e.g. so a screenshot taken on mousedown can be saved under a
// stable name before grouping – which can later merge two clicks into one doubleClick, or
// fold a key into an open `type` buffer – ever runs). This keeps `groupRawEvents` a pure
// function: it never invents ids or reads the clock, it only propagates what it is given.

export interface RawDownEvent {
  id: string
  t: number
  type: 'down'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  /** the hook's own double-click counter, when available (1 = single, 2 = second click of a pair) */
  clicks?: number
  /** a screenshot already captured around (x, y), or null when unavailable */
  shot: ScenarioShot | null
}
export interface RawUpEvent {
  t: number
  type: 'up'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
}
export interface RawWheelEvent {
  id: string
  t: number
  type: 'wheel'
  /** notches (already sign-calibrated by the capturer so positive = content scrolls down/right) */
  rotation: number
  horizontal: boolean
  x: number
  y: number
  mods: ScenarioModifiers
}
export interface RawKeyEvent {
  id: string
  t: number
  type: 'key'
  /** PC/AT set-1 scancode, low byte only (the capturer strips the 0xE000 extended marker) */
  scan: number
  /** Windows virtual-key code, resolved by keytext.ps1 */
  vk: number
  extended: boolean
  /** resolved text for this keystroke, or null when it is not text (control char, shortcut, dead key) */
  text: string | null
  mods: ScenarioModifiers
  x: number
  y: number
}
export interface RawMoveEvent {
  t: number
  type: 'move'
  x: number
  y: number
}
export type RawInputEvent = RawDownEvent | RawUpEvent | RawWheelEvent | RawKeyEvent | RawMoveEvent

export interface GroupRawEventsOptions {
  /** raw events at or after this ms (capture-relative) are ignored, e.g. the Stop click itself */
  cutoffMs?: number
}

// ---- tunables ----
const MAX_PATH_POINTS = 1200
const DRAG_THRESHOLD_PX = 6
const DOUBLE_CLICK_MS = 400
const DOUBLE_CLICK_PX = 6
const SCROLL_MERGE_MS = 400
const TYPE_MERGE_MS = 1500
// Backspace, PC/AT set-1 scancode 0x0E, never extended.
const BACKSPACE_SCAN = 14

function dist(a: ScenarioPoint, b: ScenarioPoint): number {
  return Math.hypot(a.x - b.x, a.y - b.y)
}

// Lazily created once and reused for every graphemes() call - undefined = not yet attempted,
// null = attempted and unavailable (very old runtime), so the failing `new Intl.Segmenter` is
// never retried either.
let segmenter: Intl.Segmenter | null | undefined

/** Splits text into user-perceived characters (so backspace and per-character replay are unicode-correct). */
export function graphemes(text: string): string[] {
  if (segmenter === undefined) {
    try {
      segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' })
    } catch {
      segmenter = null
    }
  }
  if (!segmenter) {
    // Intl.Segmenter is unavailable: fall back to code points, which is still surrogate-pair
    // safe even if it does not merge combining marks.
    return Array.from(text)
  }
  return Array.from(segmenter.segment(text), (s) => s.segment)
}

function popGrapheme(text: string): string {
  const g = graphemes(text)
  g.pop()
  return g.join('')
}

/** Drops repeated positions but keeps the last sample of a run, so pauses still show up as a gap in time. */
function collapseMoves(points: RawMoveEvent[]): RawMoveEvent[] {
  const out: RawMoveEvent[] = []
  for (const p of points) {
    const last = out[out.length - 1]
    if (last && last.x === p.x && last.y === p.y) out[out.length - 1] = p
    else out.push(p)
  }
  return out
}

function capPoints<T>(points: T[], max: number): T[] {
  if (points.length <= max) return points
  const out: T[] = []
  const step = points.length / max
  for (let i = 0; i < max; i++) out.push(points[Math.min(points.length - 1, Math.round(i * step))])
  out[out.length - 1] = points[points.length - 1]
  return out
}

function pathFromMoves(moves: RawMoveEvent[], baselineT: number): ScenarioPathPoint[] {
  // Points at or before the baseline belong to whatever gesture just closed (e.g. a drag's
  // own moves, still sitting in the shared pending-moves buffer) - never the next action's
  // leading path. Dropping them here (rather than merely clamping their dt to 0) means a
  // forgotten pendingMoves reset elsewhere degrades gracefully instead of prepending a run of
  // meaningless zero-dt points.
  const relevant = moves.filter((p) => p.t > baselineT)
  const collapsed = capPoints(collapseMoves(relevant), MAX_PATH_POINTS)
  const out: ScenarioPathPoint[] = []
  let last = baselineT
  for (const p of collapsed) {
    out.push({ x: p.x, y: p.y, dt: Math.max(0, p.t - last) })
    last = p.t
  }
  return out
}

// scan:extended signatures of pure modifier keys (Ctrl/Shift/Alt/Win, both sides).
const MODIFIER_SIGNATURES = new Set(['29:false', '29:true', '56:false', '56:true', '42:false', '54:false', '91:true', '92:true'])

/** Exported so the capturer can skip a wasted keytext round-trip for a bare modifier press. */
export function isModifierKey(scan: number, extended: boolean): boolean {
  return MODIFIER_SIGNATURES.has(`${scan}:${extended}`)
}

function isModifierOnly(e: RawKeyEvent): boolean {
  return isModifierKey(e.scan, e.extended)
}

// Display labels for common non-text keys, keyed by "scan:extended" using real PC/AT set-1
// scan codes. Only used for the human-readable label – replay uses scan/vk directly, so a
// key missing from this table still replays correctly, it just shows as "Key<scan>".
const KEY_NAMES: Record<string, string> = {
  '1:false': 'Escape',
  '14:false': 'Backspace',
  '15:false': 'Tab',
  '28:false': 'Enter',
  '28:true': 'NumpadEnter',
  '57:false': 'Space',
  '58:false': 'CapsLock',
  '69:false': 'NumLock',
  '70:false': 'ScrollLock',
  '82:false': 'Numpad0', '79:false': 'Numpad1', '80:false': 'Numpad2', '81:false': 'Numpad3',
  '75:false': 'Numpad4', '76:false': 'Numpad5', '77:false': 'Numpad6',
  '71:false': 'Numpad7', '72:false': 'Numpad8', '73:false': 'Numpad9',
  '83:false': 'Numpad.', '78:false': 'Numpad+', '74:false': 'Numpad-', '55:false': 'Numpad*', '53:true': 'Numpad/',
  '59:false': 'F1', '60:false': 'F2', '61:false': 'F3', '62:false': 'F4', '63:false': 'F5', '64:false': 'F6',
  '65:false': 'F7', '66:false': 'F8', '67:false': 'F9', '68:false': 'F10', '87:false': 'F11', '88:false': 'F12',
  '82:true': 'Insert', '83:true': 'Delete', '71:true': 'Home', '79:true': 'End',
  '73:true': 'PageUp', '81:true': 'PageDown',
  '75:true': 'ArrowLeft', '77:true': 'ArrowRight', '72:true': 'ArrowUp', '80:true': 'ArrowDown',
  '29:true': 'Ctrl', '56:true': 'Alt',
  '55:true': 'PrintScreen'
}

const PUNCTUATION_VK: Record<number, string> = {
  0xba: ';', 0xbb: '=', 0xbc: ',', 0xbd: '-', 0xbe: '.', 0xbf: '/',
  0xc0: '`', 0xdb: '[', 0xdc: '\\', 0xdd: ']', 0xde: "'"
}

function baseKeyLabel(e: { scan: number; vk: number; extended: boolean }): string {
  const named = KEY_NAMES[`${e.scan}:${e.extended}`]
  if (named) return named
  if (e.vk >= 48 && e.vk <= 57) return String.fromCharCode(e.vk) // 0-9
  if (e.vk >= 65 && e.vk <= 90) return String.fromCharCode(e.vk) // A-Z
  if (PUNCTUATION_VK[e.vk]) return PUNCTUATION_VK[e.vk]
  return `Key${e.scan}`
}

function describeKeyLabel(e: RawKeyEvent): string {
  const parts: string[] = []
  if (e.mods.ctrl) parts.push('Ctrl')
  if (e.mods.shift) parts.push('Shift')
  if (e.mods.alt) parts.push('Alt')
  if (e.mods.meta) parts.push('Win')
  parts.push(baseKeyLabel(e))
  return parts.join('+')
}

interface TypeBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  text: string
}
interface ScrollBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  deltaY: number
  deltaX: number
}
interface DownState {
  id: string
  t: number
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
  shot: ScenarioShot | null
  /** the leading path, snapshotted the moment the button went down */
  path: ScenarioPathPoint[]
  /** moves observed while the button is held, for a potential drag */
  moves: RawMoveEvent[]
}

/**
 * Turns a chronological stream of raw input events into scenario actions.
 *
 * Grouping rules: left down+up moving less than 6px is a click (a second one within 400ms
 * and 6px, or the hook's own `clicks === 2`, replaces it with a doubleClick); moving further
 * is a drag. Right/middle down+up become rightClick/middleClick. Wheel events closer than
 * 400ms merge into one scroll. Resolved-text keys (no Ctrl/Alt/Win) merge into one `type`
 * while consecutive keys are closer than 1.5s; Backspace inside a non-empty type buffer
 * removes the last character instead of becoming its own action. Everything else becomes a
 * `key` action. Pure modifier presses are dropped. Each action's `path` is the collapsed
 * mouse movement since the previous gesture ended.
 *
 * The result is default-timed (withDefaultTiming): `at` keeps the recorded time for ordering
 * and debugging only, how long an action takes and how long it is followed by stillness is the
 * per-action durationMs / pauseMs, which replay and the review screen both use.
 */
export function groupRawEvents(raw: RawInputEvent[], opts: GroupRawEventsOptions = {}): ScenarioAction[] {
  const cutoff = opts.cutoffMs ?? Number.POSITIVE_INFINITY
  const events = raw.filter((e) => e.t < cutoff).slice().sort((a, b) => a.t - b.t)

  const output: ScenarioAction[] = []
  let pendingMoves: RawMoveEvent[] = []
  const downs: Record<'left' | 'right' | 'middle', DownState | null> = { left: null, right: null, middle: null }
  let typeBuf: TypeBuffer | null = null
  let scrollBuf: ScrollBuffer | null = null

  // Placeholder timing for the literals below: the real defaults depend on the FINAL kind (a
  // click can still be merged into a doubleClick), so withDefaultTiming() fills them in once at the end.
  const UNTIMED = { durationMs: 0, pauseMs: 0 }
  // Recorded time at which the latest finished gesture really ended. The next action's leading
  // path only starts after it, so a closed gesture's own mouse moves (a drag's, say) never leak
  // into it. It is just this path baseline - nothing in here feeds replay timing.
  let lastEndT = 0
  const pushAction = (action: ScenarioAction, endT: number): void => {
    output.push(action)
    lastEndT = Math.max(lastEndT, endT)
  }
  const takePath = (): ScenarioPathPoint[] => {
    const path = pathFromMoves(pendingMoves, lastEndT)
    pendingMoves = []
    return path
  }
  const closeType = (): void => {
    if (!typeBuf) return
    const buf = typeBuf
    typeBuf = null
    if (buf.text.length === 0) return
    const action: ScenarioTypeAction = {
      id: buf.id, kind: 'type', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      text: buf.text, ...UNTIMED
    }
    pushAction(action, buf.lastT)
  }
  const closeScroll = (): void => {
    if (!scrollBuf) return
    const buf = scrollBuf
    scrollBuf = null
    const action: ScenarioScrollAction = {
      id: buf.id, kind: 'scroll', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      deltaY: buf.deltaY, deltaX: buf.deltaX, ...UNTIMED
    }
    pushAction(action, buf.lastT)
  }
  const closeGestures = (): void => {
    closeType()
    closeScroll()
  }
  const pushClickOrMerge = (click: ScenarioClickAction, endT: number, downClicks?: number, upClicks?: number): void => {
    const prev = output[output.length - 1]
    const isDoubleSignal = downClicks === 2 || upClicks === 2
    if (prev && prev.kind === 'click') {
      const closeInTime = click.at - prev.at <= DOUBLE_CLICK_MS
      const closeInSpace = dist(prev, click) <= DOUBLE_CLICK_PX
      // Distance always gates the merge: a hook/OS "clicks" counter can report 2 for two
      // clicks that land on completely different elements (observed live - the counter is
      // evidently time-based only on at least one real platform), so it is only trusted to
      // relax the *time* requirement, never to merge two clicks that are far apart.
      if (closeInSpace && (isDoubleSignal || closeInTime)) {
        output[output.length - 1] = { ...prev, kind: 'doubleClick' }
        lastEndT = Math.max(lastEndT, endT)
        return
      }
    }
    pushAction(click, endT)
  }
  const handleKey = (e: RawKeyEvent): void => {
    if (isModifierOnly(e)) return
    const chord = e.mods.ctrl || e.mods.alt || e.mods.meta
    const isBackspace = !chord && e.scan === BACKSPACE_SCAN && !e.extended

    if (isBackspace && typeBuf && typeBuf.text.length > 0) {
      typeBuf.text = popGrapheme(typeBuf.text)
      typeBuf.lastT = e.t
      return
    }
    if (!chord && e.text) {
      if (typeBuf && e.t - typeBuf.lastT <= TYPE_MERGE_MS) {
        typeBuf.text += e.text
        typeBuf.lastT = e.t
        return
      }
      closeGestures()
      const path = takePath()
      typeBuf = { id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path, text: e.text }
      return
    }
    // a standalone key: Enter/Tab/Escape/arrows/F-keys, Backspace on an empty buffer, or a chord
    closeGestures()
    const path = takePath()
    const action: ScenarioKeyAction = {
      id: e.id, kind: 'key', at: e.t, x: e.x, y: e.y, path, modifiers: e.mods, shot: null,
      key: describeKeyLabel(e), vk: e.vk, scan: e.scan, extended: e.extended, ...UNTIMED
    }
    pushAction(action, e.t)
  }

  for (const e of events) {
    if (e.type === 'move') {
      pendingMoves.push(e)
      if (downs.left) downs.left.moves.push(e)
      if (downs.right) downs.right.moves.push(e)
      if (downs.middle) downs.middle.moves.push(e)
      continue
    }
    if (e.type === 'down') {
      closeGestures()
      downs[e.button] = { id: e.id, t: e.t, x: e.x, y: e.y, mods: e.mods, clicks: e.clicks, shot: e.shot, path: takePath(), moves: [] }
      continue
    }
    if (e.type === 'up') {
      const down = downs[e.button]
      if (!down) continue
      downs[e.button] = null
      if (e.button === 'left') {
        if (dist(down, e) < DRAG_THRESHOLD_PX) {
          const click: ScenarioClickAction = {
            id: down.id, kind: 'click', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot, ...UNTIMED
          }
          pushClickOrMerge(click, e.t, down.clicks, e.clicks)
        } else {
          const drag: ScenarioDragAction = {
            id: down.id, kind: 'drag', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot,
            toX: e.x, toY: e.y, dragPath: pathFromMoves(down.moves, down.t), ...UNTIMED
          }
          pushAction(drag, e.t)
        }
      } else {
        const click: ScenarioClickAction = {
          id: down.id, kind: e.button === 'right' ? 'rightClick' : 'middleClick', at: down.t, x: down.x, y: down.y,
          path: down.path, modifiers: down.mods, shot: down.shot, ...UNTIMED
        }
        pushAction(click, e.t)
      }
      continue
    }
    if (e.type === 'wheel') {
      if (scrollBuf && e.t - scrollBuf.lastT <= SCROLL_MERGE_MS) {
        if (e.horizontal) scrollBuf.deltaX += e.rotation
        else scrollBuf.deltaY += e.rotation
        scrollBuf.lastT = e.t
      } else {
        closeGestures()
        scrollBuf = {
          id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path: takePath(),
          deltaY: e.horizontal ? 0 : e.rotation,
          deltaX: e.horizontal ? e.rotation : 0
        }
      }
      continue
    }
    handleKey(e)
  }

  closeGestures()
  // A gesture that started earliest does not necessarily *close* (get pushed) first: a right
  // click or key handled while a left button is still held down is pushed before the drag/click
  // that eventually closes it. Stable-sort by `at` so the output is always chronological.
  output.sort((a, b) => a.at - b.at)

  return withDefaultTiming(output)
}

// ---- timing model ----
// Since scenario v2 a replay is strictly sequential: action 0 starts at 0 and occupies
// [start, start + durationMs]; its pause (pauseMs of stillness) follows; the next action starts
// when that pause is over, and the replay ends after the last action's pause. The recorded `at`
// is never consulted - these two numbers per action are the whole timeline, so editing one of
// them can only ever move the actions after it. Everything that needs a time (the schedule, the
// replay compiler, the review screen) reads them through actionDurationMs / actionPauseMs,
// which clamp what is stored, so stored garbage can never make replay and display disagree.

export const SCENARIO_VERSION = 2
/** stillness after an action unless the user picks something else */
export const DEFAULT_PAUSE_MS = 1500
export const PAUSE_MAX_MS = 60_000
export const DURATION_MAX_MS = 60_000
/** one-click choices offered for a pause, and for the duration of every action but typing */
export const PAUSE_PRESETS_MS: readonly number[] = [1000, 1500, 2000]
export const DURATION_PRESETS_MS: readonly number[] = [1000, 1500, 2000]
export type TypeSpeed = 'fast' | 'normal' | 'slow'
/** ms per typed character (grapheme) for each typing speed preset */
export const TYPE_SPEED_MS: Record<TypeSpeed, number> = { fast: 40, normal: 80, slow: 150 }

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v))
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v)
}

/** Whole wheel notches one axis of a scroll replays as; a non-finite delta (stored garbage) counts as none. */
function wholeNotches(delta: number): number {
  return Number.isFinite(delta) ? Math.ceil(Math.abs(delta)) : 0
}

/** Number of physical wheel notches a scroll action replays as - the y and x axes are
 * independent notch streams (see compileScenario's 'scroll' case), so the total is their sum. */
function scrollNotchCount(a: ScenarioScrollAction): number {
  return wholeNotches(a.deltaY) + wholeNotches(a.deltaX)
}

/** Floor for typed text: 25ms per character at the very fastest, and never under 200ms so even
 * a one-letter action reads as an action. */
function typeMinMs(chars: number): number {
  return Math.max(200, chars * 25)
}

/**
 * Floor for a scroll. compileScenario spreads the notches over the last 60% of the action minus
 * 20ms and they must stay at least 40ms apart, so n notches need ((n - 1) * 40 + 20) / 0.6. The
 * division is written as * 5 / 3 so it is exact on whole numbers (0.6 is not representable).
 * With integer D this also survives the rounding of the 40% mark: the window is then never
 * shorter than (n - 1) * 40 ms.
 */
function scrollMinMs(notches: number): number {
  return Math.max(300, Math.ceil((((notches - 1) * 40 + 20) * 5) / 3))
}

/** `ms` rounded and held between `min` and DURATION_MAX_MS. The floor wins if it alone exceeds
 * the maximum (a scroll of about 900 notches, a text of 2400 characters): a replay must never go
 * faster than what keeps its notches / keystrokes apart, and SCENARIO_MAX_MS still bounds the total. */
function clampDuration(min: number, ms: number): number {
  return Math.max(min, Math.min(DURATION_MAX_MS, Math.round(ms)))
}

/** The shortest an action may take, ms: shorter and its phases (travel, press, release) no longer fit. */
export function minDurationMs(a: ScenarioAction): number {
  switch (a.kind) {
    case 'click':
    case 'rightClick':
    case 'middleClick': return 200
    case 'doubleClick': return 300
    case 'drag': return 500
    case 'key': return 150
    case 'type': return typeMinMs(graphemes(a.text).length)
    case 'scroll': return scrollMinMs(scrollNotchCount(a))
  }
}

/** What a fresh capture (and a migrated version-1 scenario) gives the action, ms. */
export function defaultDurationMs(a: ScenarioAction): number {
  let natural: number
  switch (a.kind) {
    case 'drag':
      natural = 1500
      break
    case 'key':
      natural = 500
      break
    case 'type':
      natural = graphemes(a.text).length * TYPE_SPEED_MS.normal
      break
    default: // the other clicks and scroll
      natural = 1000
  }
  return clampDuration(minDurationMs(a), natural)
}

/** The duration everything uses: the stored one, rounded and held within [minDurationMs, DURATION_MAX_MS]. */
export function actionDurationMs(a: ScenarioAction): number {
  if (!isFiniteNumber(a.durationMs)) return defaultDurationMs(a)
  return clampDuration(minDurationMs(a), a.durationMs)
}

/** The pause everything uses: the stored one, rounded and held within [0, PAUSE_MAX_MS]. */
export function actionPauseMs(a: ScenarioAction): number {
  if (!isFiniteNumber(a.pauseMs)) return DEFAULT_PAUSE_MS
  return clamp(Math.round(a.pauseMs), 0, PAUSE_MAX_MS)
}

/** The duration for `text` typed at a preset speed, clamped like a type action's own duration. */
export function typeDurationForSpeed(text: string, speed: TypeSpeed): number {
  const chars = graphemes(text).length
  return clampDuration(typeMinMs(chars), chars * TYPE_SPEED_MS[speed])
}

// The moment each kind "visibly happens" inside its duration. compileScenario puts the same
// moments on its steps, so the progress marker (and the review timeline) sit on the real effect.
// Offsets back from the end E: a click's button goes down 90ms before it, a double click's first
// press 180ms, a key's press 60ms. A drag presses, and a scroll starts turning, after 40% of the
// duration: the pointer has travelled there and rested by then.
const CLICK_DOWN_BEFORE_END_MS = 90
const DOUBLE_CLICK_DOWN_BEFORE_END_MS = 180
const KEY_DOWN_BEFORE_END_MS = 60

/** where, within the action's own duration `d`, its effect happens */
function effectOffsetMs(a: ScenarioAction, d: number): number {
  switch (a.kind) {
    case 'click':
    case 'rightClick':
    case 'middleClick': return d - CLICK_DOWN_BEFORE_END_MS
    case 'doubleClick': return d - DOUBLE_CLICK_DOWN_BEFORE_END_MS
    case 'drag':
    case 'scroll': return Math.round((d * 2) / 5)
    case 'type': return 0
    case 'key': return d - KEY_DOWN_BEFORE_END_MS
  }
}

export interface ScheduledAction {
  /** when the action begins (the pointer starts travelling), ms from the replay start */
  start: number
  /** when it visibly happens: the click lands, the wheel starts turning, the first character is typed. Where the replay's progress marker sits. */
  effectAt: number
  /** when the action itself is over */
  end: number
  /** when its pause is over = when the next action starts (the replay ends, after the last one) */
  pauseEnd: number
}

/** Where every action sits on the replay timeline; aligned with `actions`. See the timing model above. */
export function scenarioSchedule(actions: ScenarioAction[]): ScheduledAction[] {
  const out: ScheduledAction[] = []
  let start = 0
  for (const a of actions) {
    const d = actionDurationMs(a)
    const end = start + d
    const pauseEnd = end + actionPauseMs(a)
    out.push({ start, effectAt: start + effectOffsetMs(a, d), end, pauseEnd })
    start = pauseEnd
  }
  return out
}

/** Replay length: where the last pause ends (0 without actions). */
export function scenarioEnd(actions: ScenarioAction[]): number {
  let t = 0
  for (const a of actions) t += actionDurationMs(a) + actionPauseMs(a)
  return t
}

export type ScenarioValidationError = 'empty' | 'tooLong'

export function validateScenario(actions: ScenarioAction[]): ScenarioValidationError | null {
  if (actions.length === 0) return 'empty'
  if (scenarioEnd(actions) > SCENARIO_MAX_MS) return 'tooLong'
  return null
}

/** Gives every action its default duration and the default pause (a fresh capture, a migrated v1 file). */
export function withDefaultTiming(actions: ScenarioAction[]): ScenarioAction[] {
  return actions.map((a) => ({ ...a, durationMs: defaultDurationMs(a), pauseMs: DEFAULT_PAUSE_MS }))
}

/** Missing or non-finite timing becomes the default; a finite value is left for the accessors to clamp. */
function normalizeTiming(a: ScenarioAction): ScenarioAction {
  return {
    ...a,
    durationMs: isFiniteNumber(a.durationMs) ? a.durationMs : defaultDurationMs(a),
    pauseMs: isFiniteNumber(a.pauseMs) ? a.pauseMs : DEFAULT_PAUSE_MS
  }
}

/**
 * Brings a scenario read from disk (or anywhere else) to the current version, as a copy: the
 * input is never mutated and every field but the actions' timing is copied as is. A version-2
 * file only has unusable timing replaced by defaults. Version 1 (and a file without a version)
 * used absolute times; they are not converted - the actions get the same default timing a fresh
 * capture gets. Throws when `raw` is not a scenario at all.
 */
export function migrateScenario(raw: unknown): Scenario {
  if (typeof raw !== 'object' || raw === null || !Array.isArray((raw as { actions?: unknown }).actions)) {
    throw new Error('Not a scenario')
  }
  // typed as a current Scenario for convenience: a file from an older build lacks the timing fields
  const scenario = raw as Scenario
  const version = (raw as { version?: unknown }).version
  const actions =
    typeof version === 'number' && version >= SCENARIO_VERSION
      ? scenario.actions.map(normalizeTiming)
      : withDefaultTiming(scenario.actions)
  return { ...scenario, version: SCENARIO_VERSION, actions }
}

// ---- editing ----
// Every edit returns a new array - or the very same one when it changes nothing (an unknown id, an
// invalid number, the value already being set). Callers compare references to skip an autosave.

function patchAction(actions: ScenarioAction[], id: string, patch: (a: ScenarioAction) => ScenarioAction): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const next = patch(actions[idx])
  if (next === actions[idx]) return actions
  const out = actions.slice()
  out[idx] = next
  return out
}

/** Sets how long one action takes; rounded and held within [minDurationMs, DURATION_MAX_MS]. */
export function setActionDuration(actions: ScenarioAction[], id: string, ms: number): ScenarioAction[] {
  if (!Number.isFinite(ms)) return actions
  return patchAction(actions, id, (a) => {
    const value = clampDuration(minDurationMs(a), ms)
    return a.durationMs === value ? a : { ...a, durationMs: value }
  })
}

/** Sets the pause after one action; rounded and held within [0, PAUSE_MAX_MS]. */
export function setActionPause(actions: ScenarioAction[], id: string, ms: number): ScenarioAction[] {
  if (!Number.isFinite(ms)) return actions
  const value = clamp(Math.round(ms), 0, PAUSE_MAX_MS)
  return patchAction(actions, id, (a) => (a.pauseMs === value ? a : { ...a, pauseMs: value }))
}

/** Sets the same pause after every action (the "all pauses" presets). */
export function setAllPauses(actions: ScenarioAction[], ms: number): ScenarioAction[] {
  if (!Number.isFinite(ms)) return actions
  const value = clamp(Math.round(ms), 0, PAUSE_MAX_MS)
  if (actions.every((a) => a.pauseMs === value)) return actions
  return actions.map((a) => (a.pauseMs === value ? a : { ...a, pauseMs: value }))
}

/** Control characters (C0, DEL, C1) cannot be typed as text: Enter and Tab are `key` actions of their own. */
function stripControlChars(text: string): string {
  let out = ''
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0
    if (code < 0x20 || (code >= 0x7f && code <= 0x9f)) continue
    out += ch
  }
  return out
}

/**
 * Replaces the text of a `type` action (any other kind is left alone). The text is cleaned of
 * control characters; one that ends up empty is rejected. The duration follows the length so the
 * typing speed stays what it was (the new length times the old milliseconds per character), then
 * the usual limits apply.
 */
export function setActionText(actions: ScenarioAction[], id: string, text: string): ScenarioAction[] {
  if (typeof text !== 'string') return actions
  const clean = stripControlChars(text)
  if (clean.length === 0) return actions
  return patchAction(actions, id, (a) => {
    if (a.kind !== 'type' || a.text === clean) return a
    const before = graphemes(a.text).length
    const after = graphemes(clean).length
    const msPerChar = before > 0 ? actionDurationMs(a) / before : TYPE_SPEED_MS.normal
    return { ...a, text: clean, durationMs: clampDuration(typeMinMs(after), msPerChar * after) }
  })
}

/**
 * Drags an action along the timeline: it should start at `startMs`. Only pauses change - the
 * first action is pinned at 0, so every other start is the sum of what precedes it. With
 * `ripple` the pause before the action stretches or shrinks and everything after it shifts
 * along; a move to the right is also held back so the scenario does not grow past
 * SCENARIO_MAX_MS (a scenario already past it can only be shortened). Without `ripple` the pause
 * before the action takes the change and the action's own pause gives it back, so the next
 * action - or the end of the scenario - stays exactly where it was.
 */
export function moveActionStart(actions: ScenarioAction[], id: string, startMs: number, ripple: boolean): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx <= 0 || !Number.isFinite(startMs)) return actions
  const schedule = scenarioSchedule(actions)
  const prev = actions[idx - 1]
  const own = actions[idx]
  const prevPause = actionPauseMs(prev)
  const ownPause = actionPauseMs(own)
  const wanted = Math.round(startMs) - schedule[idx].start

  let delta: number
  if (ripple) {
    const room = Math.max(0, SCENARIO_MAX_MS - schedule[schedule.length - 1].pauseEnd)
    delta = clamp(wanted, -prevPause, Math.min(PAUSE_MAX_MS - prevPause, room))
  } else {
    delta = clamp(wanted, Math.max(-prevPause, ownPause - PAUSE_MAX_MS), Math.min(PAUSE_MAX_MS - prevPause, ownPause))
  }
  if (delta === 0) return actions

  const out = actions.slice()
  out[idx - 1] = { ...prev, pauseMs: prevPause + delta }
  if (!ripple) out[idx] = { ...own, pauseMs: ownPause - delta }
  return out
}

/** Removes an action together with its pause; the next one's recorded leading path is cleared
 * too, since it recorded movement from the now-deleted action, not from whatever now precedes
 * it. Neither path is ever replayed either way (compileScenario always moves in a straight
 * eased line, see its own doc comment) - this is purely about not keeping misleading recorded
 * data attached to an action. */
export function deleteAction(actions: ScenarioAction[], id: string): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const out = actions.filter((a) => a.id !== id)
  if (idx < out.length) out[idx] = { ...out[idx], path: [] }
  return out
}

// ---- cursor motion ----
// The user's own recorded mouse movement is never reproduced at replay (see ScenarioActionBase.path's
// doc comment). Every pointer action first TRAVELS from where the cursor is to its own point, and
// every move the compiler emits is a straight line between two points, eased in/out and sampled
// at 60Hz. The travel takes exactly the window the schedule leaves for it - the first part of the
// action's duration - so "how long the mouse needs to get there" is simply the action's own,
// editable, duration. This keeps the replayed cursor looking deliberate and synthetic rather than
// reproducing anyone's actual hand movement.

/** Same easing curve as the renderer's engine/camera.ts easeInOutCubic - copied rather than
 * imported, since shared code must not depend on renderer code. */
function easeInOutCubic(p: number): number {
  const t = clamp(p, 0, 1)
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2
}

/** How long the pointer rests on the spot between landing there and the press / first wheel
 * notch, so the cursor visibly arrives before the action happens. */
const TRAVEL_SETTLE_MS = 90
/** Modifier keys go down this long before the press they belong to. */
const MODIFIER_LEAD_MS = 20

/**
 * Samples a straight, eased cursor move from `from` to `to` between `start` and `end` (ms) into
 * `steps`, at 60Hz, landing exactly on `to` at `end`. Two points within 2px are treated as the
 * same point - the cursor is already there, so nothing is emitted. A window shorter than one
 * frame (or none) becomes a single move at `end`.
 */
function emitEasedMove(steps: ReplayStep[], from: ScenarioPoint, to: ScenarioPoint, start: number, end: number): void {
  const dx = to.x - from.x
  const dy = to.y - from.y
  if (Math.hypot(dx, dy) < 2) return
  const span = end - start
  if (span <= 0) {
    steps.push({ t: Math.max(0, Math.round(end)), op: 'move', x: to.x, y: to.y })
    return
  }
  const stepMs = 1000 / 60
  const n = Math.max(1, Math.round(span / stepMs))
  for (let i = 1; i < n; i++) {
    const e = easeInOutCubic(i / n)
    steps.push({ t: Math.round(start + span * (i / n)), op: 'move', x: from.x + dx * e, y: from.y + dy * e })
  }
  // pushed separately (rather than trusting the loop's own i===n sample) so the landing point is
  // always exactly `to`, never a floating-point near-miss
  steps.push({ t: Math.round(end), op: 'move', x: to.x, y: to.y })
}

// ---- compile to replay steps ----

export type ReplayStep =
  | { t: number; op: 'move'; x: number; y: number }
  | { t: number; op: 'down' | 'up'; button: 'left' | 'right' | 'middle' }
  | { t: number; op: 'wheel'; dy: number; dx: number } // one notch = ±120
  | { t: number; op: 'key'; vk: number; scan: number; extended: boolean; down: boolean }
  | { t: number; op: 'text'; text: string } // one grapheme, KEYEVENTF_UNICODE down+up
  | { t: number; op: 'action'; index: number } // progress marker at the action's effectAt
  | { t: number; op: 'end' } // the very end of the schedule, after the last pause: the helper reports `D` once it is reached

export interface CompileOptions {
  /** where the replay cursor sits before the very first pointer action's travel, DIP - normally
   * the captured Scenario.startPoint (see ReplaySession.create in main/scenario/replay.ts),
   * falling back to the first action's own point (no initial move) when a scenario has none. */
  startPos: ScenarioPoint
}

const MODIFIER_VK: Record<keyof ScenarioModifiers, number> = { ctrl: 0x11, shift: 0x10, alt: 0x12, meta: 0x5b }
const MODIFIER_SCAN: Record<keyof ScenarioModifiers, number> = { ctrl: 29, shift: 42, alt: 56, meta: 91 }
const MODIFIER_ORDER: Array<keyof ScenarioModifiers> = ['ctrl', 'shift', 'alt', 'meta']

function heldModifiers(m: ScenarioModifiers): Array<keyof ScenarioModifiers> {
  return MODIFIER_ORDER.filter((k) => m[k])
}
function pushModifiers(steps: ReplayStep[], mods: Array<keyof ScenarioModifiers>, t: number, down: boolean): void {
  for (const m of mods) steps.push({ t, op: 'key', vk: MODIFIER_VK[m], scan: MODIFIER_SCAN[m], extended: false, down })
}

/**
 * Compiles a scenario (or a bare action list) into a flat, time-ordered replay schedule.
 * All times are whole ms; t=0 is the moment the helper receives `GO`, which the controller sends
 * at `recording start + 800` (RecordingController.started() -> ReplaySession.go()).
 *
 * The timing is scenarioSchedule()'s: action i owns the window [start, end] and every step it
 * emits lies inside it; its pause is a stretch with no steps, and the next action starts after
 * that. So nothing can overlap, and one `end` step closes the schedule at scenarioEnd() - the
 * helper only reports `D` (done) once it is reached, which is how the final pause gets recorded.
 * The recorded `at` and the recorded mouse path are never consulted.
 *
 * Pointer actions (click, doubleClick, rightClick, middleClick, drag, scroll) first TRAVEL from
 * the cursor's current position - opts.startPos for the first one, otherwise where the previous
 * pointer action left it - to their own point, in a straight eased line that lands 90ms before
 * the press / first notch. type and key never move the cursor. With D = end - start, the steps
 * of each kind are (modifiers down / up bracket every press, 20ms before it and at `end`):
 *   click, rightClick, middleClick: travel start..end-180, down end-90 (the effect), up end-20
 *   doubleClick: travel start..end-270, down end-180 (the effect), up end-110, down end-90, up end-20
 *   drag: down at start+0.4D (the effect), travel start..down-90, then a straight eased move from
 *         (x, y) to (toX, toY) over down+40..end-40, up end-20; the cursor ends at (toX, toY)
 *   scroll: the notches are spread evenly over start+0.4D (the effect)..end-20, travel start..first-notch-90
 *   type: one grapheme at start + k * D / n, the first one (the effect) at start
 *   key: key down end-60 (the effect), up end-20
 * The shortest duration of every kind (minDurationMs) keeps all of that in order.
 */
export function compileScenario(input: Scenario | ScenarioAction[], opts: CompileOptions): ReplayStep[] {
  const actions = Array.isArray(input) ? input : input.actions
  const schedule = scenarioSchedule(actions)
  const steps: ReplayStep[] = []
  let cursor: ScenarioPoint = opts.startPos

  actions.forEach((a, i) => {
    const { start, effectAt, end } = schedule[i]
    const here: ScenarioPoint = { x: a.x, y: a.y }
    const mods = heldModifiers(a.modifiers)
    steps.push({ t: effectAt, op: 'action', index: i })

    switch (a.kind) {
      case 'click':
      case 'rightClick':
      case 'middleClick': {
        const button = a.kind === 'click' ? 'left' : a.kind === 'rightClick' ? 'right' : 'middle'
        emitEasedMove(steps, cursor, here, start, effectAt - TRAVEL_SETTLE_MS)
        pushModifiers(steps, mods, effectAt - MODIFIER_LEAD_MS, true)
        steps.push({ t: effectAt, op: 'down', button })
        steps.push({ t: end - 20, op: 'up', button })
        pushModifiers(steps, mods, end, false)
        cursor = here
        break
      }
      case 'doubleClick': {
        emitEasedMove(steps, cursor, here, start, effectAt - TRAVEL_SETTLE_MS)
        pushModifiers(steps, mods, effectAt - MODIFIER_LEAD_MS, true)
        steps.push({ t: effectAt, op: 'down', button: 'left' })
        steps.push({ t: end - 110, op: 'up', button: 'left' })
        steps.push({ t: end - 90, op: 'down', button: 'left' })
        steps.push({ t: end - 20, op: 'up', button: 'left' })
        pushModifiers(steps, mods, end, false)
        cursor = here
        break
      }
      case 'drag': {
        const to: ScenarioPoint = { x: a.toX, y: a.toY }
        emitEasedMove(steps, cursor, here, start, effectAt - TRAVEL_SETTLE_MS)
        pushModifiers(steps, mods, effectAt - MODIFIER_LEAD_MS, true)
        steps.push({ t: effectAt, op: 'down', button: 'left' })
        emitEasedMove(steps, here, to, effectAt + 40, end - 40)
        steps.push({ t: end - 20, op: 'up', button: 'left' })
        pushModifiers(steps, mods, end, false)
        cursor = to
        break
      }
      case 'scroll': {
        emitEasedMove(steps, cursor, here, start, effectAt - TRAVEL_SETTLE_MS)
        cursor = here
        // y notches first, then x ones: the two axes are independent notch streams
        const notchesY = wholeNotches(a.deltaY)
        const n = notchesY + wholeNotches(a.deltaX)
        const wheelSpan = end - 20 - effectAt
        const signY = a.deltaY < 0 ? -1 : 1
        const signX = a.deltaX < 0 ? -1 : 1
        // deltaY > 0 means "content scrolls down" (capture-side convention, calibrated
        // against a live DOM scrollTop check), but a physical MOUSEEVENTF_WHEEL notch of
        // +120 (rotated forward, away from the user) scrolls content UP - so reproducing a
        // positive deltaY needs a *negative* mouseData. Measured on this axis only; dx keeps
        // the naive (unflipped) sign until someone verifies horizontal wheel the same way.
        for (let k = 0; k < n; k++) {
          const onY = k < notchesY
          steps.push({
            t: n > 1 ? effectAt + Math.round((k * wheelSpan) / (n - 1)) : effectAt,
            op: 'wheel',
            dy: onY ? -120 * signY : 0,
            dx: onY ? 0 : 120 * signX
          })
        }
        break
      }
      case 'type': {
        const chars = graphemes(a.text)
        chars.forEach((text, k) => {
          steps.push({ t: start + Math.round((k * (end - start)) / chars.length), op: 'text', text })
        })
        break
      }
      case 'key': {
        pushModifiers(steps, mods, effectAt - MODIFIER_LEAD_MS, true)
        steps.push({ t: effectAt, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: true })
        steps.push({ t: end - 20, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: false })
        pushModifiers(steps, mods, end, false)
        break
      }
    }
  })

  steps.push({ t: scenarioEnd(actions), op: 'end' })
  steps.sort((x, y) => x.t - y.t)
  return steps
}

// ---- labels ----

export interface ActionDescription {
  kindKey: ScenarioActionKind
  /** extra plain text: the typed string, or the key/chord label – nothing here needs translation */
  detail: string
}

/** Structured label for an action, so the renderer can translate `kindKey` and just append `detail`. */
export function describeAction(a: ScenarioAction): ActionDescription {
  switch (a.kind) {
    case 'type': return { kindKey: a.kind, detail: a.text }
    case 'key': return { kindKey: a.kind, detail: a.key }
    default: return { kindKey: a.kind, detail: '' }
  }
}
