/**
 * Pure engine for the scenario recorder: shared by the main process (which compiles a
 * captured scenario into replay steps) and the renderer (the review screen, which retimes
 * and deletes actions). No Electron imports here, and no I/O – everything is deterministic
 * given its inputs, which is what makes it unit-testable without a real capture.
 */
import { SCENARIO_MAX_MS } from './defaults'
import type {
  Scenario,
  ScenarioAction,
  ScenarioActionKind,
  ScenarioClickAction,
  ScenarioDragAction,
  ScenarioKeyAction,
  ScenarioModifiers,
  ScenarioPathPoint,
  ScenarioPoint,
  ScenarioScrollAction,
  ScenarioShot,
  ScenarioTypeAction
} from './types'

// ---- raw capture events ----
// The capture module (src/main/scenario/capture.ts) turns uiohook/polling events into this
// union, in chronological order. Every event that can *start* a new action carries an `id`
// generated by the capturer (e.g. so a screenshot taken on mousedown can be saved under a
// stable name before grouping – which can later merge two clicks into one doubleClick, or
// fold a key into an open `type` buffer – ever runs). This keeps `groupRawEvents` a pure
// function: it never invents ids or reads the clock, it only propagates what it is given.

export interface RawDownEvent {
  id: string
  t: number
  type: 'down'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  /** the hook's own double-click counter, when available (1 = single, 2 = second click of a pair) */
  clicks?: number
  /** a screenshot already captured around (x, y), or null when unavailable */
  shot: ScenarioShot | null
}
export interface RawUpEvent {
  t: number
  type: 'up'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
}
export interface RawWheelEvent {
  id: string
  t: number
  type: 'wheel'
  /** notches (already sign-calibrated by the capturer so positive = content scrolls down/right) */
  rotation: number
  horizontal: boolean
  x: number
  y: number
  mods: ScenarioModifiers
}
export interface RawKeyEvent {
  id: string
  t: number
  type: 'key'
  /** PC/AT set-1 scancode, low byte only (the capturer strips the 0xE000 extended marker) */
  scan: number
  /** Windows virtual-key code, resolved by keytext.ps1 */
  vk: number
  extended: boolean
  /** resolved text for this keystroke, or null when it is not text (control char, shortcut, dead key) */
  text: string | null
  mods: ScenarioModifiers
  x: number
  y: number
}
export interface RawMoveEvent {
  t: number
  type: 'move'
  x: number
  y: number
}
export type RawInputEvent = RawDownEvent | RawUpEvent | RawWheelEvent | RawKeyEvent | RawMoveEvent

export interface GroupRawEventsOptions {
  /** raw events at or after this ms (capture-relative) are ignored, e.g. the Stop click itself */
  cutoffMs?: number
}

// ---- tunables ----
const MAX_PATH_POINTS = 1200
const DRAG_THRESHOLD_PX = 6
const DOUBLE_CLICK_MS = 400
const DOUBLE_CLICK_PX = 6
const SCROLL_MERGE_MS = 400
const TYPE_MERGE_MS = 1500
const MIN_GAP_MS = 50
/** A typed action's durationMs is never less than this many ms per character, even when the
 * keystrokes themselves were faster - otherwise a one- or two-character `type` action ends up
 * too short to read as a span on the review timeline, and replays at an unnaturally fast pace. */
const MIN_TYPE_MS_PER_CHAR = 150
/** A drag is never animated (and its button never released) faster than this, however fast the
 * recorded gesture was - see effectiveDuration(). */
const DRAG_MIN_MS = 200
// Backspace, PC/AT set-1 scancode 0x0E, never extended.
const BACKSPACE_SCAN = 14

function dist(a: ScenarioPoint, b: ScenarioPoint): number {
  return Math.hypot(a.x - b.x, a.y - b.y)
}

// Lazily created once and reused for every graphemes() call - undefined = not yet attempted,
// null = attempted and unavailable (very old runtime), so the failing `new Intl.Segmenter` is
// never retried either.
let segmenter: Intl.Segmenter | null | undefined

/** Splits text into user-perceived characters (so backspace and per-character replay are unicode-correct). */
export function graphemes(text: string): string[] {
  if (segmenter === undefined) {
    try {
      segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' })
    } catch {
      segmenter = null
    }
  }
  if (!segmenter) {
    // Intl.Segmenter is unavailable: fall back to code points, which is still surrogate-pair
    // safe even if it does not merge combining marks.
    return Array.from(text)
  }
  return Array.from(segmenter.segment(text), (s) => s.segment)
}

function popGrapheme(text: string): string {
  const g = graphemes(text)
  g.pop()
  return g.join('')
}

/** Drops repeated positions but keeps the last sample of a run, so pauses still show up as a gap in time. */
function collapseMoves(points: RawMoveEvent[]): RawMoveEvent[] {
  const out: RawMoveEvent[] = []
  for (const p of points) {
    const last = out[out.length - 1]
    if (last && last.x === p.x && last.y === p.y) out[out.length - 1] = p
    else out.push(p)
  }
  return out
}

function capPoints<T>(points: T[], max: number): T[] {
  if (points.length <= max) return points
  const out: T[] = []
  const step = points.length / max
  for (let i = 0; i < max; i++) out.push(points[Math.min(points.length - 1, Math.round(i * step))])
  out[out.length - 1] = points[points.length - 1]
  return out
}

function pathFromMoves(moves: RawMoveEvent[], baselineT: number): ScenarioPathPoint[] {
  // Points at or before the baseline belong to whatever gesture just closed (e.g. a drag's
  // own moves, still sitting in the shared pending-moves buffer) - never the next action's
  // leading path. Dropping them here (rather than merely clamping their dt to 0) means a
  // forgotten pendingMoves reset elsewhere degrades gracefully instead of prepending a run of
  // meaningless zero-dt points.
  const relevant = moves.filter((p) => p.t > baselineT)
  const collapsed = capPoints(collapseMoves(relevant), MAX_PATH_POINTS)
  const out: ScenarioPathPoint[] = []
  let last = baselineT
  for (const p of collapsed) {
    out.push({ x: p.x, y: p.y, dt: Math.max(0, p.t - last) })
    last = p.t
  }
  return out
}

// scan:extended signatures of pure modifier keys (Ctrl/Shift/Alt/Win, both sides).
const MODIFIER_SIGNATURES = new Set(['29:false', '29:true', '56:false', '56:true', '42:false', '54:false', '91:true', '92:true'])

/** Exported so the capturer can skip a wasted keytext round-trip for a bare modifier press. */
export function isModifierKey(scan: number, extended: boolean): boolean {
  return MODIFIER_SIGNATURES.has(`${scan}:${extended}`)
}

function isModifierOnly(e: RawKeyEvent): boolean {
  return isModifierKey(e.scan, e.extended)
}

// Display labels for common non-text keys, keyed by "scan:extended" using real PC/AT set-1
// scan codes. Only used for the human-readable label – replay uses scan/vk directly, so a
// key missing from this table still replays correctly, it just shows as "Key<scan>".
const KEY_NAMES: Record<string, string> = {
  '1:false': 'Escape',
  '14:false': 'Backspace',
  '15:false': 'Tab',
  '28:false': 'Enter',
  '28:true': 'NumpadEnter',
  '57:false': 'Space',
  '58:false': 'CapsLock',
  '69:false': 'NumLock',
  '70:false': 'ScrollLock',
  '82:false': 'Numpad0', '79:false': 'Numpad1', '80:false': 'Numpad2', '81:false': 'Numpad3',
  '75:false': 'Numpad4', '76:false': 'Numpad5', '77:false': 'Numpad6',
  '71:false': 'Numpad7', '72:false': 'Numpad8', '73:false': 'Numpad9',
  '83:false': 'Numpad.', '78:false': 'Numpad+', '74:false': 'Numpad-', '55:false': 'Numpad*', '53:true': 'Numpad/',
  '59:false': 'F1', '60:false': 'F2', '61:false': 'F3', '62:false': 'F4', '63:false': 'F5', '64:false': 'F6',
  '65:false': 'F7', '66:false': 'F8', '67:false': 'F9', '68:false': 'F10', '87:false': 'F11', '88:false': 'F12',
  '82:true': 'Insert', '83:true': 'Delete', '71:true': 'Home', '79:true': 'End',
  '73:true': 'PageUp', '81:true': 'PageDown',
  '75:true': 'ArrowLeft', '77:true': 'ArrowRight', '72:true': 'ArrowUp', '80:true': 'ArrowDown',
  '29:true': 'Ctrl', '56:true': 'Alt',
  '55:true': 'PrintScreen'
}

const PUNCTUATION_VK: Record<number, string> = {
  0xba: ';', 0xbb: '=', 0xbc: ',', 0xbd: '-', 0xbe: '.', 0xbf: '/',
  0xc0: '`', 0xdb: '[', 0xdc: '\\', 0xdd: ']', 0xde: "'"
}

function baseKeyLabel(e: { scan: number; vk: number; extended: boolean }): string {
  const named = KEY_NAMES[`${e.scan}:${e.extended}`]
  if (named) return named
  if (e.vk >= 48 && e.vk <= 57) return String.fromCharCode(e.vk) // 0-9
  if (e.vk >= 65 && e.vk <= 90) return String.fromCharCode(e.vk) // A-Z
  if (PUNCTUATION_VK[e.vk]) return PUNCTUATION_VK[e.vk]
  return `Key${e.scan}`
}

function describeKeyLabel(e: RawKeyEvent): string {
  const parts: string[] = []
  if (e.mods.ctrl) parts.push('Ctrl')
  if (e.mods.shift) parts.push('Shift')
  if (e.mods.alt) parts.push('Alt')
  if (e.mods.meta) parts.push('Win')
  parts.push(baseKeyLabel(e))
  return parts.join('+')
}

interface TypeBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  text: string
}
interface ScrollBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  deltaY: number
  deltaX: number
}
interface DownState {
  id: string
  t: number
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
  shot: ScenarioShot | null
  /** the leading path, snapshotted the moment the button went down */
  path: ScenarioPathPoint[]
  /** moves observed while the button is held, for a potential drag */
  moves: RawMoveEvent[]
}

/**
 * Turns a chronological stream of raw input events into scenario actions.
 *
 * Grouping rules: left down+up moving less than 6px is a click (a second one within 400ms
 * and 6px, or the hook's own `clicks === 2`, replaces it with a doubleClick); moving further
 * is a drag. Right/middle down+up become rightClick/middleClick. Wheel events closer than
 * 400ms merge into one scroll. Resolved-text keys (no Ctrl/Alt/Win) merge into one `type`
 * while consecutive keys are closer than 1.5s; Backspace inside a non-empty type buffer
 * removes the last character instead of becoming its own action. A `type` action's durationMs
 * is inflated to at least MIN_TYPE_MS_PER_CHAR per character, even if the keystrokes themselves
 * were faster, but never enough to overlap the action that follows it (or SCENARIO_MAX_MS, for
 * the last action) - see the clamping pass after the final sort below. Everything else becomes a
 * `key` action. Pure modifier presses are dropped. Each action's `path` is the collapsed
 * mouse movement since the previous action ended.
 */
export function groupRawEvents(raw: RawInputEvent[], opts: GroupRawEventsOptions = {}): ScenarioAction[] {
  const cutoff = opts.cutoffMs ?? Number.POSITIVE_INFINITY
  const events = raw.filter((e) => e.t < cutoff).slice().sort((a, b) => a.t - b.t)

  const output: ScenarioAction[] = []
  let pendingMoves: RawMoveEvent[] = []
  const downs: Record<'left' | 'right' | 'middle', DownState | null> = { left: null, right: null, middle: null }
  let typeBuf: TypeBuffer | null = null
  let scrollBuf: ScrollBuffer | null = null

  const baseline = (): number => (output.length ? actionEnd(output[output.length - 1]) : 0)
  const takePath = (): ScenarioPathPoint[] => {
    const path = pathFromMoves(pendingMoves, baseline())
    pendingMoves = []
    return path
  }
  const closeType = (): void => {
    if (!typeBuf) return
    const buf = typeBuf
    typeBuf = null
    if (buf.text.length === 0) return
    // durationMs here is still the raw recorded value - inflating it to the per-character
    // minimum happens in a pass below, once every action's final `at` is known and it can be
    // clamped to never overlap whatever comes after it.
    const action: ScenarioTypeAction = {
      id: buf.id, kind: 'type', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      text: buf.text, durationMs: Math.max(0, buf.lastT - buf.at)
    }
    output.push(action)
  }
  const closeScroll = (): void => {
    if (!scrollBuf) return
    const buf = scrollBuf
    scrollBuf = null
    const action: ScenarioScrollAction = {
      id: buf.id, kind: 'scroll', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      deltaY: buf.deltaY, deltaX: buf.deltaX, durationMs: Math.max(0, buf.lastT - buf.at)
    }
    output.push(action)
  }
  const closeGestures = (): void => {
    closeType()
    closeScroll()
  }
  const pushClickOrMerge = (click: ScenarioClickAction, downClicks?: number, upClicks?: number): void => {
    const prev = output[output.length - 1]
    const isDoubleSignal = downClicks === 2 || upClicks === 2
    if (prev && prev.kind === 'click') {
      const closeInTime = click.at - prev.at <= DOUBLE_CLICK_MS
      const closeInSpace = dist(prev, click) <= DOUBLE_CLICK_PX
      // Distance always gates the merge: a hook/OS "clicks" counter can report 2 for two
      // clicks that land on completely different elements (observed live - the counter is
      // evidently time-based only on at least one real platform), so it is only trusted to
      // relax the *time* requirement, never to merge two clicks that are far apart.
      if (closeInSpace && (isDoubleSignal || closeInTime)) {
        output[output.length - 1] = { ...prev, kind: 'doubleClick' }
        return
      }
    }
    output.push(click)
  }
  const handleKey = (e: RawKeyEvent): void => {
    if (isModifierOnly(e)) return
    const chord = e.mods.ctrl || e.mods.alt || e.mods.meta
    const isBackspace = !chord && e.scan === BACKSPACE_SCAN && !e.extended

    if (isBackspace && typeBuf && typeBuf.text.length > 0) {
      typeBuf.text = popGrapheme(typeBuf.text)
      typeBuf.lastT = e.t
      return
    }
    if (!chord && e.text) {
      if (typeBuf && e.t - typeBuf.lastT <= TYPE_MERGE_MS) {
        typeBuf.text += e.text
        typeBuf.lastT = e.t
        return
      }
      closeGestures()
      const path = takePath()
      typeBuf = { id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path, text: e.text }
      return
    }
    // a standalone key: Enter/Tab/Escape/arrows/F-keys, Backspace on an empty buffer, or a chord
    closeGestures()
    const path = takePath()
    const action: ScenarioKeyAction = {
      id: e.id, kind: 'key', at: e.t, x: e.x, y: e.y, path, modifiers: e.mods, shot: null,
      key: describeKeyLabel(e), vk: e.vk, scan: e.scan, extended: e.extended
    }
    output.push(action)
  }

  for (const e of events) {
    if (e.type === 'move') {
      pendingMoves.push(e)
      if (downs.left) downs.left.moves.push(e)
      if (downs.right) downs.right.moves.push(e)
      if (downs.middle) downs.middle.moves.push(e)
      continue
    }
    if (e.type === 'down') {
      closeGestures()
      downs[e.button] = { id: e.id, t: e.t, x: e.x, y: e.y, mods: e.mods, clicks: e.clicks, shot: e.shot, path: takePath(), moves: [] }
      continue
    }
    if (e.type === 'up') {
      const down = downs[e.button]
      if (!down) continue
      downs[e.button] = null
      if (e.button === 'left') {
        if (dist(down, e) < DRAG_THRESHOLD_PX) {
          const click: ScenarioClickAction = {
            id: down.id, kind: 'click', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot
          }
          pushClickOrMerge(click, down.clicks, e.clicks)
        } else {
          const drag: ScenarioDragAction = {
            id: down.id, kind: 'drag', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot,
            toX: e.x, toY: e.y, dragPath: pathFromMoves(down.moves, down.t), durationMs: Math.max(0, e.t - down.t)
          }
          output.push(drag)
        }
      } else {
        const click: ScenarioClickAction = {
          id: down.id, kind: e.button === 'right' ? 'rightClick' : 'middleClick', at: down.t, x: down.x, y: down.y,
          path: down.path, modifiers: down.mods, shot: down.shot
        }
        output.push(click)
      }
      continue
    }
    if (e.type === 'wheel') {
      if (scrollBuf && e.t - scrollBuf.lastT <= SCROLL_MERGE_MS) {
        if (e.horizontal) scrollBuf.deltaX += e.rotation
        else scrollBuf.deltaY += e.rotation
        scrollBuf.lastT = e.t
      } else {
        closeGestures()
        scrollBuf = {
          id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path: takePath(),
          deltaY: e.horizontal ? 0 : e.rotation,
          deltaX: e.horizontal ? e.rotation : 0
        }
      }
      continue
    }
    handleKey(e)
  }

  closeGestures()
  // A gesture that started earliest does not necessarily *close* (get pushed) first: a right
  // click or key handled while a left button is still held down is pushed before the drag/click
  // that eventually closes it. Stable-sort by `at` so the output is always chronological.
  output.sort((a, b) => a.at - b.at)

  // Inflate every `type` action's durationMs to the per-character minimum now that every
  // action's final `at` is known, clamped to the room actually available before whatever follows
  // it (or SCENARIO_MAX_MS for the last action) so the inflation can never make it overlap its
  // neighbour - but never shrunk below what was really recorded, even if that leaves no room to
  // spare (an inflated-but-clamped duration is still purely cosmetic/pacing, never a hard fact
  // about what was typed).
  for (let i = 0; i < output.length; i++) {
    const a = output[i]
    if (a.kind !== 'type') continue
    const recorded = a.durationMs
    const inflated = Math.max(recorded, MIN_TYPE_MS_PER_CHAR * graphemes(a.text).length)
    const next = output[i + 1]
    const room = (next ? next.at - MIN_GAP_MS : SCENARIO_MAX_MS) - a.at
    output[i] = { ...a, durationMs: Math.max(recorded, Math.min(inflated, room)) }
  }

  return output
}

// ---- timing ----

export function actionDuration(a: ScenarioAction): number {
  switch (a.kind) {
    case 'click': return 70
    case 'doubleClick': return 250
    case 'rightClick': return 70
    case 'middleClick': return 70
    case 'drag': return effectiveDuration(a)
    case 'scroll': return effectiveDuration(a)
    case 'type': return a.durationMs
    case 'key': return 60
  }
}

/** Number of physical wheel notches a scroll action replays as - the y and x axes are
 * independent notch streams (see compileScenario's 'scroll' case), so the total is their sum. */
function scrollNotchCount(a: ScenarioScrollAction): number {
  return Math.ceil(Math.abs(a.deltaY)) + Math.ceil(Math.abs(a.deltaX))
}

/**
 * The duration an action actually occupies once replayed or drawn, which can exceed its raw,
 * recorded `durationMs`: a drag's button never lifts faster than DRAG_MIN_MS, and a multi-notch
 * scroll is never compressed tighter than 40ms between notches (see compileScenario's 'drag' and
 * 'scroll' cases). This is the single source of truth for both floors - actionDuration (and so
 * actionEnd, scenarioEnd, retimeAction's neighbour clamps), compileScenario, and the review
 * timeline's span rendering (isSpanAction/spanWidthPx in renderer/src/scenario/format.ts) all go
 * through it, so replay timing, gap editing and the visual span can never drift apart or let a
 * fast drag/scroll overlap whatever comes after it. A `type` action's durationMs already has its
 * own per-character minimum baked in at capture time, clamped to never overlap its neighbour
 * (see groupRawEvents), so it passes through actionDuration unchanged here.
 */
export function effectiveDuration(a: ScenarioAction): number {
  if (a.kind === 'drag') return Math.max(a.durationMs, DRAG_MIN_MS)
  if (a.kind === 'scroll') return Math.max(a.durationMs, (scrollNotchCount(a) - 1) * 40)
  return actionDuration(a)
}

export function actionEnd(a: ScenarioAction): number {
  return a.at + actionDuration(a)
}

export function scenarioEnd(actions: ScenarioAction[]): number {
  return actions.reduce((max, a) => Math.max(max, actionEnd(a)), 0)
}

export type ScenarioValidationError = 'empty' | 'tooLong'

export function validateScenario(actions: ScenarioAction[]): ScenarioValidationError | null {
  if (actions.length === 0) return 'empty'
  if (scenarioEnd(actions) > SCENARIO_MAX_MS) return 'tooLong'
  return null
}

/**
 * Moves one action. Clamped so it keeps a >= 50ms gap from its neighbours, never goes
 * negative, and never pushes any action's end past SCENARIO_MAX_MS. With `ripple`, every
 * following action shifts by the same delta (so their mutual gaps are untouched) instead of
 * being limited by the very next action.
 */
export function retimeAction(actions: ScenarioAction[], id: string, at: number, ripple: boolean): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const action = actions[idx]
  const prev = idx > 0 ? actions[idx - 1] : undefined
  const minAt = prev ? actionEnd(prev) + MIN_GAP_MS : 0

  if (!ripple) {
    const next = actions[idx + 1]
    const ownMax = SCENARIO_MAX_MS - actionDuration(action)
    const maxAt = Math.min(ownMax, next ? next.at - MIN_GAP_MS - actionDuration(action) : ownMax)
    // No room to move without violating a constraint (neighbours packed tighter than a single
    // move could satisfy): leave it where it is rather than clamping into an overlap.
    if (maxAt < minAt) return actions
    const clamped = Math.min(Math.max(at, minAt), maxAt)
    if (clamped === action.at) return actions
    return actions.map((a, i) => (i === idx ? { ...a, at: clamped } : a))
  }

  const last = actions[actions.length - 1]
  const maxDelta = SCENARIO_MAX_MS - actionEnd(last)
  const minDelta = minAt - action.at
  if (maxDelta < minDelta) return actions
  const delta = Math.min(Math.max(at - action.at, minDelta), maxDelta)
  if (delta === 0) return actions
  return actions.map((a, i) => (i >= idx ? { ...a, at: a.at + delta } : a))
}

/** Removes an action; the next one's recorded leading path is cleared too, since it recorded
 * movement from the now-deleted action, not from whatever now precedes it. Neither path is ever
 * replayed either way (compileScenario always moves in a straight eased line, see its own doc
 * comment) - this is purely about not keeping misleading recorded data attached to an action. */
export function deleteAction(actions: ScenarioAction[], id: string): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const out = actions.filter((a) => a.id !== id)
  if (idx < out.length) out[idx] = { ...out[idx], path: [] }
  return out
}

/** How far into a normalized capture the first action should sit; see normalizeLeadIn(). */
const NORMALIZE_LEAD_MS = 1000

/**
 * Called once, right after grouping (capture.ts's finish()), to trim away dead time before the
 * user's very first action: when the first action's `at` is more than NORMALIZE_LEAD_MS, every
 * action is shifted left by the same amount so the first one lands exactly at
 * NORMALIZE_LEAD_MS. This avoids replaying (and recording) tens of seconds of nothing when the
 * user took a while to start after the countdown ended, while still leaving a believable moment
 * of lead-in - and the user can always retime the first action deliberately in the review
 * screen afterwards. Recorded paths are untouched (they are not replayed either way - see
 * ScenarioActionBase.path's doc comment), only the absolute `at` of every action changes.
 */
export function normalizeLeadIn(actions: ScenarioAction[]): ScenarioAction[] {
  if (actions.length === 0) return actions
  const at0 = actions[0].at
  if (at0 <= NORMALIZE_LEAD_MS) return actions
  const delta = at0 - NORMALIZE_LEAD_MS
  return actions.map((a) => ({ ...a, at: a.at - delta }))
}

// ---- cursor motion ----
// The user's own recorded mouse movement is never reproduced at replay (see ScenarioActionBase.path's
// doc comment) - every move the compiler emits is a straight line between two points, eased in/out
// and timed from the distance travelled, at 60Hz. This keeps the replayed cursor looking deliberate
// and synthetic rather than reproducing anyone's actual hand movement.

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v))
}

/** Same easing curve as the renderer's engine/camera.ts easeInOutCubic - copied rather than
 * imported, since shared code must not depend on renderer code. */
function easeInOutCubic(p: number): number {
  const t = clamp(p, 0, 1)
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2
}

/** How long before an action's own effect fires the leading move finishes, so the cursor
 * visibly rests before the action happens. */
const MOVE_SETTLE_MS = 90
/** Below this gap between the previous action's end and this one, an eased move is not worth
 * animating - the cursor just jumps, shortly before the action fires. */
const MOVE_MIN_GAP_MS = 120

/**
 * Samples a straight, eased cursor move from `from` to `to` between `start` and `end` (ms) into
 * `steps`, at 60Hz, landing exactly on `to` at `end`. Two points within 2px are treated as the
 * same point - the cursor is already there, so nothing is emitted.
 */
function emitEasedMove(steps: ReplayStep[], from: ScenarioPoint, to: ScenarioPoint, start: number, end: number): void {
  const dx = to.x - from.x
  const dy = to.y - from.y
  if (Math.hypot(dx, dy) < 2) return
  const span = end - start
  if (span <= 0) {
    // clamped like every other step (see pushModifiers) - end is not guaranteed >= 0 for every
    // caller/input combination, even though it is for the ones in this file today
    steps.push({ t: Math.max(0, Math.round(end)), op: 'move', x: to.x, y: to.y })
    return
  }
  const stepMs = 1000 / 60
  const n = Math.max(1, Math.round(span / stepMs))
  for (let i = 1; i < n; i++) {
    const e = easeInOutCubic(i / n)
    steps.push({ t: Math.round(start + span * (i / n)), op: 'move', x: from.x + dx * e, y: from.y + dy * e })
  }
  // pushed separately (rather than trusting the loop's own i===n sample) so the landing point is
  // always exactly `to`, never a floating-point near-miss
  steps.push({ t: Math.round(end), op: 'move', x: to.x, y: to.y })
}

/**
 * Lays out the leading move from `from` (the previous action's resting point, or the scenario's
 * start position for the very first action) to `to` (this action's own point), finishing
 * MOVE_SETTLE_MS before `at`. A gap under MOVE_MIN_GAP_MS is not worth animating - the cursor
 * just jumps to the target 10ms before `at`. The move's duration grows with distance (a short
 * hop is quick, a long one takes longer to feel natural) but never eats more than 80% of the
 * available gap, and never starts before `prevEnd` (the previous action's own end).
 */
function layOutLeadingMove(steps: ReplayStep[], from: ScenarioPoint, to: ScenarioPoint, prevEnd: number, at: number): void {
  if (Math.hypot(to.x - from.x, to.y - from.y) < 2) return
  const gap = at - prevEnd
  if (gap < MOVE_MIN_GAP_MS) {
    // clamped like every other step (see pushModifiers) - reachable when the very first action
    // sits at a tiny `at` (the review screen allows retiming it down to 0)
    steps.push({ t: Math.max(0, Math.round(at - 10)), op: 'move', x: to.x, y: to.y })
    return
  }
  const distance = dist(from, to)
  const duration = Math.min(clamp(220 + distance * 0.45, 260, 900), 0.8 * gap)
  const end = at - MOVE_SETTLE_MS
  const start = Math.max(prevEnd, end - duration)
  emitEasedMove(steps, from, to, start, end)
}

// ---- compile to replay steps ----

export type ReplayStep =
  | { t: number; op: 'move'; x: number; y: number }
  | { t: number; op: 'down' | 'up'; button: 'left' | 'right' | 'middle' }
  | { t: number; op: 'wheel'; dy: number; dx: number } // one notch = ±120
  | { t: number; op: 'key'; vk: number; scan: number; extended: boolean; down: boolean }
  | { t: number; op: 'text'; text: string } // one grapheme, KEYEVENTF_UNICODE down+up
  | { t: number; op: 'action'; index: number } // progress marker at the action's `at`

export interface CompileOptions {
  /** where the replay cursor sits before the very first action's leading move, DIP - normally
   * the captured Scenario.startPoint (see ReplaySession.create in main/scenario/replay.ts),
   * falling back to the first action's own point (no initial move) when a scenario has none. */
  startPos: ScenarioPoint
}

const MODIFIER_VK: Record<keyof ScenarioModifiers, number> = { ctrl: 0x11, shift: 0x10, alt: 0x12, meta: 0x5b }
const MODIFIER_SCAN: Record<keyof ScenarioModifiers, number> = { ctrl: 29, shift: 42, alt: 56, meta: 91 }
const MODIFIER_ORDER: Array<keyof ScenarioModifiers> = ['ctrl', 'shift', 'alt', 'meta']

function heldModifiers(m: ScenarioModifiers): Array<keyof ScenarioModifiers> {
  return MODIFIER_ORDER.filter((k) => m[k])
}
function pushModifiers(steps: ReplayStep[], mods: Array<keyof ScenarioModifiers>, t: number, down: boolean): void {
  // a modifier-down step is scheduled 20ms before its action's `at`, which can be negative
  // for an action at the very start of the schedule (at < 20) - every step time is >= 0.
  const tt = Math.max(0, t)
  for (const m of mods) steps.push({ t: tt, op: 'key', vk: MODIFIER_VK[m], scan: MODIFIER_SCAN[m], extended: false, down })
}

/**
 * Compiles a scenario (or a bare action list) into a flat, time-ordered replay schedule.
 * All times are ms; t=0 is the moment the helper receives `GO`, which the controller sends at
 * `recording start + 800` (RecordingController.started() -> ReplaySession.go()). Every action's
 * `at` is used literally here - compileScenario never shifts the schedule as a whole. The
 * recorded mouse path is never consulted: every leading move, and every drag's own move, is a
 * straight line between two points eased in/out and timed from the distance travelled (see
 * layOutLeadingMove / emitEasedMove above) - the goal is deliberate, synthetic cursor motion,
 * not a reproduction of the user's own hand movement. A drag's button never lifts, and a multi-
 * notch scroll's notches never space out, faster than effectiveDuration() allows - the same
 * floor actionDuration/actionEnd use - so a fast drag or scroll can never overlap whatever comes
 * after it. The cursor starts at `opts.startPos` (normally the captured Scenario.startPoint);
 * every emitted step is additionally clamped to >= 0 (see pushModifiers), so nothing here ever
 * needs a negative timestamp. A capture where the
 * user took a while before the first action is expected to already have been normalized once,
 * right after grouping, by normalizeLeadIn().
 */
export function compileScenario(input: Scenario | ScenarioAction[], opts: CompileOptions): ReplayStep[] {
  const actions = Array.isArray(input) ? input : input.actions
  const steps: ReplayStep[] = []
  let cursor: ScenarioPoint = opts.startPos

  actions.forEach((a, i) => {
    const prevEnd = i === 0 ? 0 : actionEnd(actions[i - 1])
    layOutLeadingMove(steps, cursor, { x: a.x, y: a.y }, prevEnd, a.at)
    cursor = { x: a.x, y: a.y }
    steps.push({ t: a.at, op: 'action', index: i })

    const mods = heldModifiers(a.modifiers)
    switch (a.kind) {
      case 'click':
      case 'rightClick':
      case 'middleClick': {
        const button = a.kind === 'click' ? 'left' : a.kind === 'rightClick' ? 'right' : 'middle'
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button })
        steps.push({ t: a.at + 70, op: 'up', button })
        pushModifiers(steps, mods, a.at + 90, false)
        break
      }
      case 'doubleClick': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button: 'left' })
        steps.push({ t: a.at + 70, op: 'up', button: 'left' })
        steps.push({ t: a.at + 90, op: 'down', button: 'left' })
        steps.push({ t: a.at + 160, op: 'up', button: 'left' })
        pushModifiers(steps, mods, a.at + 180, false)
        break
      }
      case 'drag': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button: 'left' })
        const dragMs = effectiveDuration(a)
        emitEasedMove(steps, { x: a.x, y: a.y }, { x: a.toX, y: a.toY }, a.at, a.at + dragMs)
        steps.push({ t: a.at + dragMs, op: 'up', button: 'left' })
        pushModifiers(steps, mods, a.at + dragMs + 20, false)
        cursor = { x: a.toX, y: a.toY }
        break
      }
      case 'scroll': {
        const notches: Array<'y' | 'x'> = []
        for (let k = 0; k < Math.ceil(Math.abs(a.deltaY)); k++) notches.push('y')
        for (let k = 0; k < Math.ceil(Math.abs(a.deltaX)); k++) notches.push('x')
        if (notches.length > 0) {
          const span = effectiveDuration(a)
          const step = notches.length > 1 ? span / (notches.length - 1) : 0
          const signY = a.deltaY < 0 ? -1 : 1
          const signX = a.deltaX < 0 ? -1 : 1
          // deltaY > 0 means "content scrolls down" (capture-side convention, calibrated
          // against a live DOM scrollTop check), but a physical MOUSEEVENTF_WHEEL notch of
          // +120 (rotated forward, away from the user) scrolls content UP - so reproducing a
          // positive deltaY needs a *negative* mouseData. Measured on this axis only; dx keeps
          // the naive (unflipped) sign until someone verifies horizontal wheel the same way.
          notches.forEach((axis, k) => {
            steps.push({
              t: Math.round(a.at + k * step),
              op: 'wheel',
              dy: axis === 'y' ? -120 * signY : 0,
              dx: axis === 'x' ? 120 * signX : 0
            })
          })
        }
        break
      }
      case 'type': {
        const chars = graphemes(a.text)
        if (chars.length > 0) {
          const spacing = Math.max(25, a.durationMs / chars.length)
          chars.forEach((ch, k) => {
            steps.push({ t: Math.round(a.at + k * spacing), op: 'text', text: ch })
          })
        }
        break
      }
      case 'key': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: true })
        steps.push({ t: a.at + 40, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: false })
        pushModifiers(steps, mods, a.at + 60, false)
        break
      }
    }
  })

  steps.sort((x, y) => x.t - y.t)
  return steps
}

// ---- labels ----

export interface ActionDescription {
  kindKey: ScenarioActionKind
  /** extra plain text: the typed string, or the key/chord label – nothing here needs translation */
  detail: string
}

/** Structured label for an action, so the renderer can translate `kindKey` and just append `detail`. */
export function describeAction(a: ScenarioAction): ActionDescription {
  switch (a.kind) {
    case 'type': return { kindKey: a.kind, detail: a.text }
    case 'key': return { kindKey: a.kind, detail: a.key }
    default: return { kindKey: a.kind, detail: '' }
  }
}
