/**
 * Pure engine for the scenario recorder: shared by the main process (which compiles a
 * captured scenario into replay steps) and the renderer (the review screen, which retimes
 * and deletes actions). No Electron imports here, and no I/O – everything is deterministic
 * given its inputs, which is what makes it unit-testable without a real capture.
 */
import { SCENARIO_MAX_MS } from './defaults'
import type {
  Scenario,
  ScenarioAction,
  ScenarioActionKind,
  ScenarioClickAction,
  ScenarioDragAction,
  ScenarioKeyAction,
  ScenarioModifiers,
  ScenarioPathPoint,
  ScenarioPoint,
  ScenarioScrollAction,
  ScenarioShot,
  ScenarioTypeAction
} from './types'

// ---- raw capture events ----
// The capture module (src/main/scenario/capture.ts) turns uiohook/polling events into this
// union, in chronological order. Every event that can *start* a new action carries an `id`
// generated by the capturer (e.g. so a screenshot taken on mousedown can be saved under a
// stable name before grouping – which can later merge two clicks into one doubleClick, or
// fold a key into an open `type` buffer – ever runs). This keeps `groupRawEvents` a pure
// function: it never invents ids or reads the clock, it only propagates what it is given.

export interface RawDownEvent {
  id: string
  t: number
  type: 'down'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  /** the hook's own double-click counter, when available (1 = single, 2 = second click of a pair) */
  clicks?: number
  /** a screenshot already captured around (x, y), or null when unavailable */
  shot: ScenarioShot | null
}
export interface RawUpEvent {
  t: number
  type: 'up'
  button: 'left' | 'right' | 'middle'
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
}
export interface RawWheelEvent {
  id: string
  t: number
  type: 'wheel'
  /** notches (already sign-calibrated by the capturer so positive = content scrolls down/right) */
  rotation: number
  horizontal: boolean
  x: number
  y: number
  mods: ScenarioModifiers
}
export interface RawKeyEvent {
  id: string
  t: number
  type: 'key'
  /** PC/AT set-1 scancode, low byte only (the capturer strips the 0xE000 extended marker) */
  scan: number
  /** Windows virtual-key code, resolved by keytext.ps1 */
  vk: number
  extended: boolean
  /** resolved text for this keystroke, or null when it is not text (control char, shortcut, dead key) */
  text: string | null
  mods: ScenarioModifiers
  x: number
  y: number
}
export interface RawMoveEvent {
  t: number
  type: 'move'
  x: number
  y: number
}
export type RawInputEvent = RawDownEvent | RawUpEvent | RawWheelEvent | RawKeyEvent | RawMoveEvent

export interface GroupRawEventsOptions {
  /** raw events at or after this ms (capture-relative) are ignored, e.g. the Stop click itself */
  cutoffMs?: number
}

// ---- tunables ----
const MAX_PATH_POINTS = 1200
const DRAG_THRESHOLD_PX = 6
const DOUBLE_CLICK_MS = 400
const DOUBLE_CLICK_PX = 6
const SCROLL_MERGE_MS = 400
const TYPE_MERGE_MS = 1500
const MIN_GAP_MS = 50
// Backspace, PC/AT set-1 scancode 0x0E, never extended.
const BACKSPACE_SCAN = 14

function dist(a: ScenarioPoint, b: ScenarioPoint): number {
  return Math.hypot(a.x - b.x, a.y - b.y)
}

/** Splits text into user-perceived characters (so backspace and per-character replay are unicode-correct). */
export function graphemes(text: string): string[] {
  try {
    const segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' })
    return Array.from(segmenter.segment(text), (s) => s.segment)
  } catch {
    // Intl.Segmenter is unavailable (very old runtime): fall back to code points, which is
    // still surrogate-pair safe even if it does not merge combining marks.
    return Array.from(text)
  }
}

function popGrapheme(text: string): string {
  const g = graphemes(text)
  g.pop()
  return g.join('')
}

/** Drops repeated positions but keeps the last sample of a run, so pauses still show up as a gap in time. */
function collapseMoves(points: RawMoveEvent[]): RawMoveEvent[] {
  const out: RawMoveEvent[] = []
  for (const p of points) {
    const last = out[out.length - 1]
    if (last && last.x === p.x && last.y === p.y) out[out.length - 1] = p
    else out.push(p)
  }
  return out
}

function capPoints<T>(points: T[], max: number): T[] {
  if (points.length <= max) return points
  const out: T[] = []
  const step = points.length / max
  for (let i = 0; i < max; i++) out.push(points[Math.min(points.length - 1, Math.round(i * step))])
  out[out.length - 1] = points[points.length - 1]
  return out
}

function pathFromMoves(moves: RawMoveEvent[], baselineT: number): ScenarioPathPoint[] {
  // Points at or before the baseline belong to whatever gesture just closed (e.g. a drag's
  // own moves, still sitting in the shared pending-moves buffer) - never the next action's
  // leading path. Dropping them here (rather than merely clamping their dt to 0) means a
  // forgotten pendingMoves reset elsewhere degrades gracefully instead of prepending a run of
  // meaningless zero-dt points.
  const relevant = moves.filter((p) => p.t > baselineT)
  const collapsed = capPoints(collapseMoves(relevant), MAX_PATH_POINTS)
  const out: ScenarioPathPoint[] = []
  let last = baselineT
  for (const p of collapsed) {
    out.push({ x: p.x, y: p.y, dt: Math.max(0, p.t - last) })
    last = p.t
  }
  return out
}

// scan:extended signatures of pure modifier keys (Ctrl/Shift/Alt/Win, both sides).
const MODIFIER_SIGNATURES = new Set(['29:false', '29:true', '56:false', '56:true', '42:false', '54:false', '91:true', '92:true'])

/** Exported so the capturer can skip a wasted keytext round-trip for a bare modifier press. */
export function isModifierKey(scan: number, extended: boolean): boolean {
  return MODIFIER_SIGNATURES.has(`${scan}:${extended}`)
}

function isModifierOnly(e: RawKeyEvent): boolean {
  return isModifierKey(e.scan, e.extended)
}

// Display labels for common non-text keys, keyed by "scan:extended" using real PC/AT set-1
// scan codes. Only used for the human-readable label – replay uses scan/vk directly, so a
// key missing from this table still replays correctly, it just shows as "Key<scan>".
const KEY_NAMES: Record<string, string> = {
  '1:false': 'Escape',
  '14:false': 'Backspace',
  '15:false': 'Tab',
  '28:false': 'Enter',
  '28:true': 'NumpadEnter',
  '57:false': 'Space',
  '58:false': 'CapsLock',
  '69:false': 'NumLock',
  '70:false': 'ScrollLock',
  '82:false': 'Numpad0', '79:false': 'Numpad1', '80:false': 'Numpad2', '81:false': 'Numpad3',
  '75:false': 'Numpad4', '76:false': 'Numpad5', '77:false': 'Numpad6',
  '71:false': 'Numpad7', '72:false': 'Numpad8', '73:false': 'Numpad9',
  '83:false': 'Numpad.', '78:false': 'Numpad+', '74:false': 'Numpad-', '55:false': 'Numpad*', '53:true': 'Numpad/',
  '59:false': 'F1', '60:false': 'F2', '61:false': 'F3', '62:false': 'F4', '63:false': 'F5', '64:false': 'F6',
  '65:false': 'F7', '66:false': 'F8', '67:false': 'F9', '68:false': 'F10', '87:false': 'F11', '88:false': 'F12',
  '82:true': 'Insert', '83:true': 'Delete', '71:true': 'Home', '79:true': 'End',
  '73:true': 'PageUp', '81:true': 'PageDown',
  '75:true': 'ArrowLeft', '77:true': 'ArrowRight', '72:true': 'ArrowUp', '80:true': 'ArrowDown',
  '29:true': 'Ctrl', '56:true': 'Alt',
  '55:true': 'PrintScreen'
}

const PUNCTUATION_VK: Record<number, string> = {
  0xba: ';', 0xbb: '=', 0xbc: ',', 0xbd: '-', 0xbe: '.', 0xbf: '/',
  0xc0: '`', 0xdb: '[', 0xdc: '\\', 0xdd: ']', 0xde: "'"
}

function baseKeyLabel(e: { scan: number; vk: number; extended: boolean }): string {
  const named = KEY_NAMES[`${e.scan}:${e.extended}`]
  if (named) return named
  if (e.vk >= 48 && e.vk <= 57) return String.fromCharCode(e.vk) // 0-9
  if (e.vk >= 65 && e.vk <= 90) return String.fromCharCode(e.vk) // A-Z
  if (PUNCTUATION_VK[e.vk]) return PUNCTUATION_VK[e.vk]
  return `Key${e.scan}`
}

function describeKeyLabel(e: RawKeyEvent): string {
  const parts: string[] = []
  if (e.mods.ctrl) parts.push('Ctrl')
  if (e.mods.shift) parts.push('Shift')
  if (e.mods.alt) parts.push('Alt')
  if (e.mods.meta) parts.push('Win')
  parts.push(baseKeyLabel(e))
  return parts.join('+')
}

interface TypeBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  text: string
}
interface ScrollBuffer {
  id: string
  at: number
  lastT: number
  x: number
  y: number
  mods: ScenarioModifiers
  path: ScenarioPathPoint[]
  deltaY: number
  deltaX: number
}
interface DownState {
  id: string
  t: number
  x: number
  y: number
  mods: ScenarioModifiers
  clicks?: number
  shot: ScenarioShot | null
  /** the leading path, snapshotted the moment the button went down */
  path: ScenarioPathPoint[]
  /** moves observed while the button is held, for a potential drag */
  moves: RawMoveEvent[]
}

/**
 * Turns a chronological stream of raw input events into scenario actions.
 *
 * Grouping rules: left down+up moving less than 6px is a click (a second one within 400ms
 * and 6px, or the hook's own `clicks === 2`, replaces it with a doubleClick); moving further
 * is a drag. Right/middle down+up become rightClick/middleClick. Wheel events closer than
 * 400ms merge into one scroll. Resolved-text keys (no Ctrl/Alt/Win) merge into one `type`
 * while consecutive keys are closer than 1.5s; Backspace inside a non-empty type buffer
 * removes the last character instead of becoming its own action. Everything else becomes a
 * `key` action. Pure modifier presses are dropped. Each action's `path` is the collapsed
 * mouse movement since the previous action ended.
 */
export function groupRawEvents(raw: RawInputEvent[], opts: GroupRawEventsOptions = {}): ScenarioAction[] {
  const cutoff = opts.cutoffMs ?? Number.POSITIVE_INFINITY
  const events = raw.filter((e) => e.t < cutoff).slice().sort((a, b) => a.t - b.t)

  const output: ScenarioAction[] = []
  let pendingMoves: RawMoveEvent[] = []
  const downs: Record<'left' | 'right' | 'middle', DownState | null> = { left: null, right: null, middle: null }
  let typeBuf: TypeBuffer | null = null
  let scrollBuf: ScrollBuffer | null = null

  const baseline = (): number => (output.length ? actionEnd(output[output.length - 1]) : 0)
  const takePath = (): ScenarioPathPoint[] => {
    const path = pathFromMoves(pendingMoves, baseline())
    pendingMoves = []
    return path
  }
  const closeType = (): void => {
    if (!typeBuf) return
    const buf = typeBuf
    typeBuf = null
    if (buf.text.length === 0) return
    const action: ScenarioTypeAction = {
      id: buf.id, kind: 'type', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      text: buf.text, durationMs: Math.max(0, buf.lastT - buf.at)
    }
    output.push(action)
  }
  const closeScroll = (): void => {
    if (!scrollBuf) return
    const buf = scrollBuf
    scrollBuf = null
    const action: ScenarioScrollAction = {
      id: buf.id, kind: 'scroll', at: buf.at, x: buf.x, y: buf.y,
      path: buf.path, modifiers: buf.mods, shot: null,
      deltaY: buf.deltaY, deltaX: buf.deltaX, durationMs: Math.max(0, buf.lastT - buf.at)
    }
    output.push(action)
  }
  const closeGestures = (): void => {
    closeType()
    closeScroll()
  }
  const pushClickOrMerge = (click: ScenarioClickAction, downClicks?: number, upClicks?: number): void => {
    const prev = output[output.length - 1]
    const isDoubleSignal = downClicks === 2 || upClicks === 2
    if (prev && prev.kind === 'click') {
      const closeInTime = click.at - prev.at <= DOUBLE_CLICK_MS
      const closeInSpace = dist(prev, click) <= DOUBLE_CLICK_PX
      // Distance always gates the merge: a hook/OS "clicks" counter can report 2 for two
      // clicks that land on completely different elements (observed live - the counter is
      // evidently time-based only on at least one real platform), so it is only trusted to
      // relax the *time* requirement, never to merge two clicks that are far apart.
      if (closeInSpace && (isDoubleSignal || closeInTime)) {
        output[output.length - 1] = { ...prev, kind: 'doubleClick' }
        return
      }
    }
    output.push(click)
  }
  const handleKey = (e: RawKeyEvent): void => {
    if (isModifierOnly(e)) return
    const chord = e.mods.ctrl || e.mods.alt || e.mods.meta
    const isBackspace = !chord && e.scan === BACKSPACE_SCAN && !e.extended

    if (isBackspace && typeBuf && typeBuf.text.length > 0) {
      typeBuf.text = popGrapheme(typeBuf.text)
      typeBuf.lastT = e.t
      return
    }
    if (!chord && e.text) {
      if (typeBuf && e.t - typeBuf.lastT <= TYPE_MERGE_MS) {
        typeBuf.text += e.text
        typeBuf.lastT = e.t
        return
      }
      closeGestures()
      const path = takePath()
      typeBuf = { id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path, text: e.text }
      return
    }
    // a standalone key: Enter/Tab/Escape/arrows/F-keys, Backspace on an empty buffer, or a chord
    closeGestures()
    const path = takePath()
    const action: ScenarioKeyAction = {
      id: e.id, kind: 'key', at: e.t, x: e.x, y: e.y, path, modifiers: e.mods, shot: null,
      key: describeKeyLabel(e), vk: e.vk, scan: e.scan, extended: e.extended
    }
    output.push(action)
  }

  for (const e of events) {
    if (e.type === 'move') {
      pendingMoves.push(e)
      if (downs.left) downs.left.moves.push(e)
      if (downs.right) downs.right.moves.push(e)
      if (downs.middle) downs.middle.moves.push(e)
      continue
    }
    if (e.type === 'down') {
      closeGestures()
      downs[e.button] = { id: e.id, t: e.t, x: e.x, y: e.y, mods: e.mods, clicks: e.clicks, shot: e.shot, path: takePath(), moves: [] }
      continue
    }
    if (e.type === 'up') {
      const down = downs[e.button]
      if (!down) continue
      downs[e.button] = null
      if (e.button === 'left') {
        if (dist(down, e) < DRAG_THRESHOLD_PX) {
          const click: ScenarioClickAction = {
            id: down.id, kind: 'click', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot
          }
          pushClickOrMerge(click, down.clicks, e.clicks)
        } else {
          const drag: ScenarioDragAction = {
            id: down.id, kind: 'drag', at: down.t, x: down.x, y: down.y,
            path: down.path, modifiers: down.mods, shot: down.shot,
            toX: e.x, toY: e.y, dragPath: pathFromMoves(down.moves, down.t), durationMs: Math.max(0, e.t - down.t)
          }
          output.push(drag)
        }
      } else {
        const click: ScenarioClickAction = {
          id: down.id, kind: e.button === 'right' ? 'rightClick' : 'middleClick', at: down.t, x: down.x, y: down.y,
          path: down.path, modifiers: down.mods, shot: down.shot
        }
        output.push(click)
      }
      continue
    }
    if (e.type === 'wheel') {
      if (scrollBuf && e.t - scrollBuf.lastT <= SCROLL_MERGE_MS) {
        if (e.horizontal) scrollBuf.deltaX += e.rotation
        else scrollBuf.deltaY += e.rotation
        scrollBuf.lastT = e.t
      } else {
        closeGestures()
        scrollBuf = {
          id: e.id, at: e.t, lastT: e.t, x: e.x, y: e.y, mods: e.mods, path: takePath(),
          deltaY: e.horizontal ? 0 : e.rotation,
          deltaX: e.horizontal ? e.rotation : 0
        }
      }
      continue
    }
    handleKey(e)
  }

  closeGestures()
  // A gesture that started earliest does not necessarily *close* (get pushed) first: a right
  // click or key handled while a left button is still held down is pushed before the drag/click
  // that eventually closes it. Stable-sort by `at` so the output is always chronological.
  output.sort((a, b) => a.at - b.at)
  return output
}

// ---- timing ----

export function actionDuration(a: ScenarioAction): number {
  switch (a.kind) {
    case 'click': return 70
    case 'doubleClick': return 250
    case 'rightClick': return 70
    case 'middleClick': return 70
    case 'drag': return a.durationMs
    case 'scroll': return a.durationMs
    case 'type': return a.durationMs
    case 'key': return 60
  }
}

export function actionEnd(a: ScenarioAction): number {
  return a.at + actionDuration(a)
}

export function scenarioEnd(actions: ScenarioAction[]): number {
  return actions.reduce((max, a) => Math.max(max, actionEnd(a)), 0)
}

export type ScenarioValidationError = 'empty' | 'tooLong'

export function validateScenario(actions: ScenarioAction[]): ScenarioValidationError | null {
  if (actions.length === 0) return 'empty'
  if (scenarioEnd(actions) > SCENARIO_MAX_MS) return 'tooLong'
  return null
}

/**
 * Moves one action. Clamped so it keeps a >= 50ms gap from its neighbours, never goes
 * negative, and never pushes any action's end past SCENARIO_MAX_MS. With `ripple`, every
 * following action shifts by the same delta (so their mutual gaps are untouched) instead of
 * being limited by the very next action.
 */
export function retimeAction(actions: ScenarioAction[], id: string, at: number, ripple: boolean): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const action = actions[idx]
  const prev = idx > 0 ? actions[idx - 1] : undefined
  const minAt = prev ? actionEnd(prev) + MIN_GAP_MS : 0

  if (!ripple) {
    const next = actions[idx + 1]
    const ownMax = SCENARIO_MAX_MS - actionDuration(action)
    const maxAt = Math.min(ownMax, next ? next.at - MIN_GAP_MS - actionDuration(action) : ownMax)
    // No room to move without violating a constraint (neighbours packed tighter than a single
    // move could satisfy): leave it where it is rather than clamping into an overlap.
    if (maxAt < minAt) return actions
    const clamped = Math.min(Math.max(at, minAt), maxAt)
    if (clamped === action.at) return actions
    return actions.map((a, i) => (i === idx ? { ...a, at: clamped } : a))
  }

  const last = actions[actions.length - 1]
  const maxDelta = SCENARIO_MAX_MS - actionEnd(last)
  const minDelta = minAt - action.at
  if (maxDelta < minDelta) return actions
  const delta = Math.min(Math.max(at - action.at, minDelta), maxDelta)
  if (delta === 0) return actions
  return actions.map((a, i) => (i >= idx ? { ...a, at: a.at + delta } : a))
}

/** Removes an action; the next one loses its recorded path (it gets synthesized at replay). */
export function deleteAction(actions: ScenarioAction[], id: string): ScenarioAction[] {
  const idx = actions.findIndex((a) => a.id === id)
  if (idx === -1) return actions
  const out = actions.filter((a) => a.id !== id)
  if (idx < out.length) out[idx] = { ...out[idx], path: [] }
  return out
}

/** How far into a normalized capture the first action should sit; see normalizeLeadIn(). */
const NORMALIZE_LEAD_MS = 1000

/**
 * Called once, right after grouping (capture.ts's finish()), to trim away dead time before the
 * user's very first action: when the first action's `at` is more than NORMALIZE_LEAD_MS, every
 * action is shifted left by the same amount so the first one lands exactly at
 * NORMALIZE_LEAD_MS. This avoids replaying (and recording) tens of seconds of nothing when the
 * user took a while to start after the countdown ended, while still leaving a believable moment
 * of lead-in - and the user can always retime the first action deliberately in the review
 * screen afterwards. Recorded paths are untouched (they keep their own dts; compileScenario
 * fits them into whatever gap results), only the absolute `at` of every action changes.
 */
export function normalizeLeadIn(actions: ScenarioAction[]): ScenarioAction[] {
  if (actions.length === 0) return actions
  const at0 = actions[0].at
  if (at0 <= NORMALIZE_LEAD_MS) return actions
  const delta = at0 - NORMALIZE_LEAD_MS
  return actions.map((a) => ({ ...a, at: a.at - delta }))
}

// ---- path synthesis ----

function easeInOut(t: number): number {
  return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2
}

/** Deterministic per-endpoint sign, so the same two points always bulge the same way. */
function hashSign(a: ScenarioPoint, b: ScenarioPoint): 1 | -1 {
  const n = Math.round(a.x) + Math.round(b.y) * 3 + Math.round(a.y) * 7 + Math.round(b.x) * 11
  return n % 2 === 0 ? 1 : -1
}

/** Eased quadratic-Bézier path from `from` to `to` with a small perpendicular bulge, at 60Hz. */
export function synthesizePath(from: ScenarioPoint, to: ScenarioPoint, durationMs: number, stepMs = 1000 / 60): ScenarioPathPoint[] {
  const distance = dist(from, to)
  if (durationMs <= 0 || distance < 1) return []
  const steps = Math.max(1, Math.round(durationMs / stepMs))
  const dx = to.x - from.x
  const dy = to.y - from.y
  const bulge = distance * 0.08 * hashSign(from, to)
  const nx = -dy / distance
  const ny = dx / distance
  const midX = from.x + dx / 2 + nx * bulge
  const midY = from.y + dy / 2 + ny * bulge

  const points: ScenarioPathPoint[] = []
  let lastT = 0
  for (let i = 1; i <= steps; i++) {
    const t = i / steps
    const e = easeInOut(t)
    const omt = 1 - e
    const x = omt * omt * from.x + 2 * omt * e * midX + e * e * to.x
    const y = omt * omt * from.y + 2 * omt * e * midY + e * e * to.y
    const pointT = Math.round(t * durationMs)
    points.push({ x, y, dt: pointT - lastT })
    lastT = pointT
  }
  return points
}

// ---- compile to replay steps ----

export type ReplayStep =
  | { t: number; op: 'move'; x: number; y: number }
  | { t: number; op: 'down' | 'up'; button: 'left' | 'right' | 'middle' }
  | { t: number; op: 'wheel'; dy: number; dx: number } // one notch = ±120
  | { t: number; op: 'key'; vk: number; scan: number; extended: boolean; down: boolean }
  | { t: number; op: 'text'; text: string } // one grapheme, KEYEVENTF_UNICODE down+up
  | { t: number; op: 'action'; index: number } // progress marker at the action's `at`

export interface CompileOptions {
  /** how much runway the very first action gets to approach its target, capped by its own `at` */
  leadMs: number
  startPos: ScenarioPoint
}

const MODIFIER_VK: Record<keyof ScenarioModifiers, number> = { ctrl: 0x11, shift: 0x10, alt: 0x12, meta: 0x5b }
const MODIFIER_SCAN: Record<keyof ScenarioModifiers, number> = { ctrl: 29, shift: 42, alt: 56, meta: 91 }
const MODIFIER_ORDER: Array<keyof ScenarioModifiers> = ['ctrl', 'shift', 'alt', 'meta']

function heldModifiers(m: ScenarioModifiers): Array<keyof ScenarioModifiers> {
  return MODIFIER_ORDER.filter((k) => m[k])
}
function pushModifiers(steps: ReplayStep[], mods: Array<keyof ScenarioModifiers>, t: number, down: boolean): void {
  // a modifier-down step is scheduled 20ms before its action's `at`, which can be negative
  // for an action at the very start of the schedule (at < 20) - every step time is >= 0.
  const tt = Math.max(0, t)
  for (const m of mods) steps.push({ t: tt, op: 'key', vk: MODIFIER_VK[m], scan: MODIFIER_SCAN[m], extended: false, down })
}

/**
 * Lays out the recorded (or synthesized) leading path of an action between `gapStart` and
 * `gapEnd`, always landing exactly on `to` at `gapEnd`. A gap under 120ms is not worth
 * animating – the cursor just jumps. A recorded path keeps its own dts if they fit in the
 * gap, otherwise they are scaled down; an empty path is synthesized, ending 60ms early so
 * the cursor visibly rests before the action fires.
 */
function layOutLeadingPath(steps: ReplayStep[], recorded: ScenarioPathPoint[], from: ScenarioPoint, to: ScenarioPoint, gapStart: number, gapEnd: number): void {
  const gap = gapEnd - gapStart
  if (gap < 120) {
    steps.push({ t: gapEnd, op: 'move', x: to.x, y: to.y })
    return
  }
  if (recorded.length > 0) {
    const total = recorded.reduce((sum, p) => sum + p.dt, 0)
    const scale = total > gap ? gap / total : 1
    let t = gapStart
    for (const p of recorded) {
      t += p.dt * scale
      steps.push({ t: Math.round(t), op: 'move', x: p.x, y: p.y })
    }
    steps.push({ t: gapEnd, op: 'move', x: to.x, y: to.y })
    return
  }
  if (dist(from, to) < 1) return
  const duration = Math.min(gap, Math.max(250, 0.9 * dist(from, to)))
  const end = gapEnd - 60
  const start = Math.max(gapStart, end - duration)
  let t = start
  for (const p of synthesizePath(from, to, end - start)) {
    t += p.dt
    steps.push({ t: Math.round(t), op: 'move', x: p.x, y: p.y })
  }
}

/** The drag's own path, always rescaled to fill `durationMs` exactly and land on `to`. */
function layOutDragPath(steps: ReplayStep[], recorded: ScenarioPathPoint[], from: ScenarioPoint, to: ScenarioPoint, startT: number, durationMs: number): void {
  if (durationMs <= 0) {
    steps.push({ t: startT, op: 'move', x: to.x, y: to.y })
    return
  }
  const points = recorded.length > 0 ? recorded : synthesizePath(from, to, durationMs)
  if (points.length > 0) {
    const total = points.reduce((sum, p) => sum + p.dt, 0) || durationMs
    const scale = durationMs / total
    let t = startT
    for (const p of points) {
      t += p.dt * scale
      steps.push({ t: Math.round(t), op: 'move', x: p.x, y: p.y })
    }
  }
  steps.push({ t: startT + durationMs, op: 'move', x: to.x, y: to.y })
}

/**
 * Compiles a scenario (or a bare action list) into a flat, time-ordered replay schedule.
 * All times are ms; t=0 is the moment the helper receives `GO`, which the controller sends at
 * `recording start + leadMs` (RecordingController.started() -> ReplaySession.go()). Every
 * action's `at` is used literally here - compileScenario never shifts the schedule as a whole,
 * `leadMs` only bounds how much runway the very first action gets to approach its target,
 * capped by its own recorded `at`, so nothing here ever needs a negative timestamp (every
 * emitted step is additionally clamped to >= 0, see pushModifiers). A capture where the user
 * took a while before the first action is expected to already have been normalized once, right
 * after grouping, by normalizeLeadIn() - compileScenario itself does not do that, so replaying
 * an un-normalized scenario still starts its first action `leadMs` after `GO`, not at a fixed
 * offset.
 */
export function compileScenario(input: Scenario | ScenarioAction[], opts: CompileOptions): ReplayStep[] {
  const actions = Array.isArray(input) ? input : input.actions
  const steps: ReplayStep[] = []
  let cursor: ScenarioPoint = opts.startPos

  actions.forEach((a, i) => {
    const gapStart = i === 0 ? Math.max(0, a.at - opts.leadMs) : actionEnd(actions[i - 1])
    layOutLeadingPath(steps, a.path, cursor, { x: a.x, y: a.y }, gapStart, a.at)
    cursor = { x: a.x, y: a.y }
    steps.push({ t: a.at, op: 'action', index: i })

    const mods = heldModifiers(a.modifiers)
    switch (a.kind) {
      case 'click':
      case 'rightClick':
      case 'middleClick': {
        const button = a.kind === 'click' ? 'left' : a.kind === 'rightClick' ? 'right' : 'middle'
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button })
        steps.push({ t: a.at + 70, op: 'up', button })
        pushModifiers(steps, mods, a.at + 90, false)
        break
      }
      case 'doubleClick': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button: 'left' })
        steps.push({ t: a.at + 70, op: 'up', button: 'left' })
        steps.push({ t: a.at + 90, op: 'down', button: 'left' })
        steps.push({ t: a.at + 160, op: 'up', button: 'left' })
        pushModifiers(steps, mods, a.at + 180, false)
        break
      }
      case 'drag': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'down', button: 'left' })
        layOutDragPath(steps, a.dragPath, { x: a.x, y: a.y }, { x: a.toX, y: a.toY }, a.at, a.durationMs)
        steps.push({ t: a.at + a.durationMs, op: 'up', button: 'left' })
        pushModifiers(steps, mods, a.at + a.durationMs + 20, false)
        cursor = { x: a.toX, y: a.toY }
        break
      }
      case 'scroll': {
        const notches: Array<'y' | 'x'> = []
        for (let k = 0; k < Math.ceil(Math.abs(a.deltaY)); k++) notches.push('y')
        for (let k = 0; k < Math.ceil(Math.abs(a.deltaX)); k++) notches.push('x')
        if (notches.length > 0) {
          const span = Math.max(a.durationMs, (notches.length - 1) * 40)
          const step = notches.length > 1 ? span / (notches.length - 1) : 0
          const signY = a.deltaY < 0 ? -1 : 1
          const signX = a.deltaX < 0 ? -1 : 1
          // deltaY > 0 means "content scrolls down" (capture-side convention, calibrated
          // against a live DOM scrollTop check), but a physical MOUSEEVENTF_WHEEL notch of
          // +120 (rotated forward, away from the user) scrolls content UP - so reproducing a
          // positive deltaY needs a *negative* mouseData. Measured on this axis only; dx keeps
          // the naive (unflipped) sign until someone verifies horizontal wheel the same way.
          notches.forEach((axis, k) => {
            steps.push({
              t: Math.round(a.at + k * step),
              op: 'wheel',
              dy: axis === 'y' ? -120 * signY : 0,
              dx: axis === 'x' ? 120 * signX : 0
            })
          })
        }
        break
      }
      case 'type': {
        const chars = graphemes(a.text)
        if (chars.length > 0) {
          const spacing = Math.max(25, a.durationMs / chars.length)
          chars.forEach((ch, k) => {
            steps.push({ t: Math.round(a.at + k * spacing), op: 'text', text: ch })
          })
        }
        break
      }
      case 'key': {
        pushModifiers(steps, mods, a.at - 20, true)
        steps.push({ t: a.at, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: true })
        steps.push({ t: a.at + 40, op: 'key', vk: a.vk, scan: a.scan, extended: a.extended, down: false })
        pushModifiers(steps, mods, a.at + 60, false)
        break
      }
    }
  })

  steps.sort((x, y) => x.t - y.t)
  return steps
}

// ---- labels ----

export interface ActionDescription {
  kindKey: ScenarioActionKind
  /** extra plain text: the typed string, or the key/chord label – nothing here needs translation */
  detail: string
}

/** Structured label for an action, so the renderer can translate `kindKey` and just append `detail`. */
export function describeAction(a: ScenarioAction): ActionDescription {
  switch (a.kind) {
    case 'type': return { kindKey: a.kind, detail: a.text }
    case 'key': return { kindKey: a.kind, detail: a.key }
    default: return { kindKey: a.kind, detail: '' }
  }
}
